oleneyl/maplestory_dpm_calc

dpmModule/jobs/darknight.py
=> fix beholder impact

dpmModule/jobs/kinesis.py
=> Kinesis issue

dpmModule/jobs/jobclass/demon.py
#43 에서 나왔던 지적사항을 적용했습니다.
4개의 축복이 돌아가면서 발동되므로 이계의 공허는 16초마다 한번 발동됩니다.
나머지 축복들은 딜에 영향을 주지 않습니다.
=> 이계의 여신 공격확률 수정

dpmModule/kernel/core.py, dpmModule/util/dpmgenerator.py, test.py
Max damage restriction handling argument added.
=> Add restrict argument

dpmModule/jobs/dualblade.py, test.py
듀얼블레이드 로직 수정 및 타수분할(미러이미징 최종뎀 해제)
=> Dualblade split

dpmModule/jobs/dualblade.py
Mirror imaging working not correctly, fixed.
=> Fix dualblade error

dpmModule/jobs/cadena.py
=> Fix maelstorm improper value

dpmModule/jobs/aran.py
Snow charge active damage buff was duplicated, so removed one.
=> Fix duplicated snow charge buff

dpmModule/kernel/core.py
For unavoiable situation, enable accessing runtime context by GraphElement.
in this version, only runtime_context_modifier is supported.
This commit may result simulation speed down.
For enable this option, call enable_referring_runtime_context() in initializer and re-write _use() method with **kwargs option.
=> Enable runtime context

dpmModule/jobs/striker.py
https://github.com/oleneyl/maplestory_dpm_calc/issues/126
* 하이퍼 최적으로 변경
* 태풍에 잘못 적용된 하이퍼 뎀퍼 제거
* 교아탄의 연계 최종뎀이 뎀퍼로 되던것 수정
=> 스트라이커 스킬 수정

dpmModule/kernel/core.py
#138  Hot fix
최대 데미지 반영항이 잘못 계산되던 오류를 수정
=> Fix max damage restriction error

dpmModule/kernel/core.py
Using integration of min(xy, M) over uniform distribution [x1,x2],[y1,y2]
=> Update max damage calculation logic

dpmModule/item/Arcane.py, dpmModule/item/ItemKernel.py
* 단검으로 적용되도록 수정
* 해결된 주석 제거
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/148
=> fix: 듀블 주무기에 블레이드를 착용하고 있었음

dpmModule/character/characterTemplateHigh.py
* 21퍼로 적용해야 하나 15%로 되고 있었음
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/132
=> fix: 유니온 8000 무기류 에디

dpmModule/jobs/contrib.py, dpmModule/jobs/demonslayer.py, dpmModule/jobs/dualblade.py, dpmModule/jobs/globalSkill.py, dpmModule/jobs/jobclass/resistance.py, dpmModule/jobs/shadower.py
* `jobs/demonslayer.py`: 블루 블러드로 인한 추가 타격이 최종 데미지 형태로 적용되고 있어 별도의 스킬로 분리했습니다.
* `jobs/globalSkill.py`: ~~미하일 링크스킬을 추가했습니다.~~ 중복되는 값을 람다식으로 통합했습니다.
* 다른 PR에 미하일 링크스킬이 추가되어 있어 여기서는 뺐습니다.
* `jobs/jobclass/resistance.py`: 레지스탕스 라인 인팬트리에 별도의 modifier를 삽입할 수 있게 변경했습니다.
=> 공용 스킬 코드 수정, 데슬 블블 추가타 분리

dpmModule/jobs/hero.py
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/146
=> fix: 히어로 스킬

.gitignore, dpmModule/jobs/zero.py, full_test.py
* 제로: 리밋브 지속시간 중에 추가 공속을 얻기 때문에 오라를 디바인 포스로 바꿔서 공격력 20을 얻을 수 있습니다.
* `full_test.py`: 이제 작업 내용을 실시간으로 띄워줍니다. 소요시간 측정 기능도 추가했습니다. 출력 파일이 Git에서 제외됩니다.
=> 제로 디바인포스 활용, 테스트 스크립트 수정

dpmModule/jobs/hoyoung.py
클라이언트에서 확인 가능한 호영 스킬 정보만 받아썼습니다.
앞으로 해야 할 작업 목록입니다.
1. 스킬 종류별로 정렬 (공격스킬 / 버프스킬)
2. 스킬 딜레이 추가
3. 딜사이클 구현 및 변수 수정
=> Initial commit (hoyoung.py)

dpmModule/jobs/aran.py
* 인스톨 마하 눈보라 퍼뎀 수정
* 인스톨 마하 눈보라 미발동 수정
* 콤보 어빌리티 미적용 수정
* optimization_hint 추가
https://github.com/oleneyl/maplestory_dpm_calc/issues/184
=> fix: 아란 스킬

dpmModule/jobs/flamewizard.py
* 패시브 이름들 한글화
* 인페르노라이즈 뎀퍼로 잘못 적용된것 최종뎀으로
* 디스차지 타수 수정
* 디스차지 4스택 경우 추가
* 인플서 전분 기반으로 타수 변경
* 인페르노라이즈 사용 타이밍 수정
=> fix: 플위 스킬

dpmModule/kernel/core.py
onAfter, onBefore의 등록에 따른 시전순서를 명확히 합니다.
=> Change execution order of after, before

dpmModule/jobs/jobbranch/warriors.py, dpmModule/jobs/soulmaster.py
* 엘리멘탈 엑스퍼트, 엘리멘탈 하모니 효과 뒤바뀜
* 라이징 선 / 폴링 문 효과 정확히 적용
* 셀레스티얼 추가타 코강 우선순위 셀레스티얼과 일치시킴
* 소울 이클립스 퍼뎀 수정
* 솔루나 디바이드에 딜레이 추가
* 엘리시온 균열 3번만 터지게 수정
* 오라 웨폰에 폴링 문 적용
=> fix: 소울마스터 스킬

dpmModule/character/characterKernel.py, dpmModule/kernel/core.py
* 유니온 공격대원의 스탯은 스탯% 적용 안됨
* 호영 패파 추가로 인한 덱,럭 공격대원 수 늘어남
* MDF 로그에 stat_fixed 추가
=> fix: package 과정의 유니온 공격대원 적용

dpmModule/kernel/core.py
Reverts oleneyl/maplestory_dpm_calc#165
=> Revert "Change execution order of after, before"

dpmModule/jobs/windBreaker.py
* 엘리멘탈 엑스퍼트 / 엘리멘탈 하모니 효과 뒤바뀜
* 컴뱃 오더스 수치 기입
* docstring 수정
* 알바트로스 맥시멈 버프명 수정
* 아이들 윔 도트뎀 수정
* 핀포인트 피어스에 윔,스톰브링어 발동
* optimization_hint 최적화
* 아이들 윔에 도트 데미지 미발동 수정
=> fix: 윈드브레이커 스킬

dpmModule/jobs/demonslayer.py
* 풀공속 공식이 반올림이 아닌 올림인 것을 반영
https://github.com/oleneyl/maplestory_dpm_calc/issues/215
=> fix: 데몬 슬래시(강화) 딜레이

dpmModule/jobs/aran.py, dpmModule/jobs/cannonshooter.py, dpmModule/jobs/hero.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/nightwalker.py, dpmModule/jobs/paladin.py, dpmModule/jobs/zero.py
* 아란 저지먼트 지속뎀을 도트로 변경
* 캐슈 몽키 퓨리어스(도트) 추가
* 히어로 인사이징(도트) 추가
* 키네시스 싸이킥 포스3을 도트로 변경, 퍼뎀 수정
* 나워 다크니스 도트 발동되게 수정
* 팔라딘 라이트닝 차지 도트 발동되게 수정
* 제로 디바인 리어 추가
=> fix: 도트 스킬

dpmModule/jobs/archmageFb.py, dpmModule/jobs/jobclass/adventurer.py
* 패럴 딜레이 570 -> 600
* 도퍼 딜레이 870 -> 690
* 노바 딜레이 750 -> 570
* 이프리트 딜레이 900 -> 600
* 퓨오이 딜레이 1000 -> 480
* 인피니티 딜레이 900 -> 600
* 이프리트 도트 추가
* 도퍼 사용 전에 텔마로 도퍼 +1
* 노바-도퍼 순으로 사용해 도퍼+1
* 이그나이트 빠진 스킬 추가
* 메테오(패시브)
* 파이어 오라
* 메테오 패시브 빠진 스킬 추가
* 미스트 이럽션
* 포이즌 노바
* 이프리트가 메테오 패시브를 발동시키지 않음
=> fix: 불독 스킬

dpmModule/jobs/cannonshooter.py, dpmModule/jobs/jobbranch/pirates.py
* 몽키 퓨리어스 690 -> 720
* 오크통 룰렛 810 -> 840
* 롤링 캐논 레인보우 810 -> 480
* ICBM 1190 -> 1140
* 롤링 캐논 레인보우 25타 -> 26타
* 몽키 퓨리어스 도트 퍼뎀 수정
=> fix: 캐슈 스킬 딜레이

full_test.py
full_test.py가 너무 오래 걸려서 멀티스레딩을 하도록 했습니다.
하는 김에 argument를 추가해서 테스트할 유니온 레벨들, 시뮬레이션 시간, 스레드 수를 설정할 수 있습니다.
벤치마크 결과 thread=4 기준 308.688s -> 99.167s으로 빨라집니다.
출력 형식은 이전과 동일하게 해두었으나, write_results쪽 구현을 변경하면 출력 형식을 변경할 수 있습니다.
example)
`python3 full_test.py --ulevel 6000 8000 --time 360 --thread 4`
=> feat: full_test.py 멀티스레딩

dpmModule/jobs/flamewizard.py, dpmModule/kernel/core.py
=> fix: 플레임위자드 이그니션 미발동 오류

dpmModule/jobs/adele.py, dpmModule/jobs/aran.py, dpmModule/jobs/blaster.py, dpmModule/jobs/darknight.py, dpmModule/jobs/demonavenger.py, dpmModule/jobs/demonslayer.py, dpmModule/jobs/hero.py, dpmModule/jobs/jobbranch/warriors.py, dpmModule/jobs/kaiser.py, dpmModule/jobs/michael.py, dpmModule/jobs/paladin.py, dpmModule/jobs/soulmaster.py, dpmModule/jobs/zero.py
#286 보고 만들어봤는데 아직 protect_from_running은 적용하지 않았습니다.
아직 이걸 잘 몰라서 그런데 참고할만한 자료 있을까요?
=> 오라웨폰 구현방식 변경

dpmModule/jobs/demonslayer.py
* 불필요한 오라웨폰 클래스 상속을 제거함
* 블루 블러드 스킬명 오타 수정
=> refactor: 데몬슬레이어 오라웨폰 블루블러드 로직

dpmModule/jobs/angelicbuster.py, dpmModule/jobs/aran.py, dpmModule/jobs/archmageFb.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/cannonshooter.py, dpmModule/jobs/darknight.py, dpmModule/jobs/demonslayer.py, dpmModule/jobs/dualblade.py, dpmModule/jobs/eunwol.py, dpmModule/jobs/flamewizard.py, dpmModule/jobs/globalSkill.py, dpmModule/jobs/hero.py, dpmModule/jobs/jobbranch/bowmen.py, dpmModule/jobs/jobbranch/pirates.py, dpmModule/jobs/jobbranch/thieves.py, dpmModule/jobs/jobbranch/warriors.py, dpmModule/jobs/jobclass/cygnus.py, dpmModule/jobs/jobclass/demon.py, dpmModule/jobs/jobclass/heroes.py, dpmModule/jobs/jobclass/resistance.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/mechanic.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/phantom.py, dpmModule/jobs/shadower.py, dpmModule/jobs/sniper.py, dpmModule/jobs/soulmaster.py, dpmModule/jobs/striker.py, dpmModule/jobs/windBreaker.py
은월은 쿨타임 더미에 의존하는 Rule이 있어 일부 추가 수정했습니다.
=> fix: 지금까지 확인한 직업 쿨감여부 일괄적용

dpmModule/jobs/shadower.py
* 픽파킷과 메소 익스플로전 스킬 분리
* 메소 익스플로전을 픽파킷을 참조하는 StackDamageSkill로 정의
변경 전/후 dpm, 점유율 동일한 것 확인했습니다.
=> refactor: 섀도어 메소 익스플로전

dpmModule/jobs/adele.py, dpmModule/jobs/angelicbuster.py, dpmModule/jobs/aran.py, dpmModule/jobs/battlemage.py, dpmModule/jobs/blaster.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/cadena.py, dpmModule/jobs/cannonshooter.py, dpmModule/jobs/darknight.py, dpmModule/jobs/demonslayer.py, dpmModule/jobs/dualblade.py, dpmModule/jobs/eunwol.py, dpmModule/jobs/evan.py, dpmModule/jobs/flamewizard.py, dpmModule/jobs/hero.py, dpmModule/jobs/hoyoung.py, dpmModule/jobs/ilium.py, dpmModule/jobs/kaiser.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/mercedes.py
#270
알파벳순으로 진행중입니다. 다른 직업들도 완성되는대로 업데이트하도록 하겠습니다.
메용에 컴뱃 레벨 넣는 건 전직업 완료되고 일괄적으로 할 계획입니다.
=> 컴뱃 오더스 적용 (진행중)

dpmModule/jobs/archmageTc.py
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/313
=> fix: 썬콜 프로스트 이펙트가 번개 속성에만 데미지 증가 효과를 줌

dpmModule/jobs/evan.py
* 5개당 증가하는 퍼뎀이 잘못 적용된것 수정
* 패시브 레벨을 받도록 수정
=> fix: 에반 마법 잔해 퍼뎀

dpmModule/jobs/kinesis.py
* 얼티메이트-트레인에 BPM의 컴뱃 효과 추가
* 무빙 매터 막타, 불릿 블랙홀에 각성 크뎀 추가
=> fix: 키네시스 스킬

dpmModule/jobs/shadower.py
* 다크사이트 아닐시 절개 연계 빼먹은것 추가
* 프리마 크리티컬 평균 크뎀 8.33% (150 / 18 = 8.33...)
=> Fix shadower

dpmModule/jobs/jobutils.py, dpmModule/jobs/kaiser.py, dpmModule/kernel/core.py
* SkillWrapper에 get_hit, get_damage, get_delay를 오버라이딩해서 동작을 바꿀 수 있게 함
* 윌 오브 소드 소환, 공격 단계 분리
* 윌 오브 소드:스트라이크 지속시간이 10초 이내로 남았으면 윌 오브 소드를 소환만 해두고 기다리도록 함
=> fix: 카이저 리팩토링

dpmModule/jobs/archmageFb.py, dpmModule/jobs/archmageTc.py, dpmModule/jobs/demonavenger.py
불독, 썬콜, 데몬어벤져 컴뱃 오더스 적용
불독: 이프리트에 지속시간 적용
데몬어벤져: 디펜스 엑스퍼타이즈에 실드 체이싱 공격력 20% 추가
=> Apply combat orders (3)

dpmModule/jobs/cannonshooter.py, dpmModule/jobs/captain.py, dpmModule/jobs/mechanic.py, dpmModule/jobs/viper.py
자체 럭키다이스가 있는 4개 직업에 대한 컴뱃오더스 적용분입니다.
=> 릭키다이스 컴뱃오더스 적용

dpmModule/jobs/angelicbuster.py
* 이너 파이어가 부스탯을 되어있던것을 주스탯으로 수정 (fix #344)
* 어피니티 IV 가동률 적용 (fix #345)
=> fix: 엔버 패시브

dpmModule/jobs/angelicbuster.py
* 기존에 평균으로 적용하던 스택을 시뮬레이션 중에 추적하도록 함
* docstring 동기화
=> fix: 엔젤릭버스터 트리니티 버프 중첩 시뮬레이션

dpmModule/jobs/angelicbuster.py
=> fix: 엔젤릭버스터 딜사이클

dpmModule/execution/rules.py, dpmModule/jobs/aran.py, dpmModule/jobs/ark.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/eunwol.py, dpmModule/jobs/evan.py, dpmModule/jobs/jobclass/heroes.py, dpmModule/jobs/kaiser.py, dpmModule/jobs/luminous.py, dpmModule/jobs/phantom.py, dpmModule/kernel/core.py
* 프리드의 가호 다시 만듬
* calculate_cooltime에 쿨타임을 직접 넘길수 있게 함
* UniquenessRule을 적용할 지 결정하는 uniqueFlag 추가
* 지금까지 점검한 직업 중 프리드 사용시 dpm 하락하는 경우 딜사이클에서 제거함
=> fix: 프리드의 가호 동작하게 수정

dpmModule/jobs/ark.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/jobclass/heroes.py, dpmModule/kernel/core.py
* get_cooltime()을 오버라이딩 하는 방식으로 변경
=> refactor: 프리드 구현하면서 변경한 calculate_cooltime 정의 롤백

dpmModule/kernel/core.py
* BuffSkillWrapper의 _end, onEnd() 사용되지 않으므로 제거
* Simulator.run_individual_task() 사용되지 않으므로 제거
* AbstractSkillWrapper._use() 인자 잘못된것 수정
* SummonSkillWrapper.get_delay() 빠진것 추가
=> refactor: deprecate된 메소드 제거

dpmModule/jobs/aran.py, dpmModule/jobs/archmageFb.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/cadena.py, dpmModule/jobs/cannonshooter.py, dpmModule/jobs/dualblade.py, dpmModule/jobs/evan.py, dpmModule/jobs/flamewizard.py, dpmModule/jobs/hero.py, dpmModule/jobs/hoyoung.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/nightwalker.py, dpmModule/jobs/paladin.py, dpmModule/jobs/shadower.py, dpmModule/jobs/windBreaker.py, dpmModule/jobs/zero.py, dpmModule/kernel/core.py
* DotSkill에 summondelay, delay, hit 인자 추가
* DotSkill의 cooltime 디폴트 0으로 변경
* 보우마스터 독화살 도트 타수 수정
* 에반 브레스-돌아와! SummonSkill로 수정
* 히어로 인사이징 2초 주기로 수정
* 듀블, 섀도어 페이탈 베놈 타수에 패시브 레벨 반영
* 듀블, 섀도어 페이탈 베놈 발동 안되던것 수정
* 불독 슬라임 바이러스, 포이즌 브레스 도트 데미지 적용되게 수정
* 불독 도트 발동이 밀리던 현상 수정
* 카데나 출혈 발동 안되던것 수정
=> fix: 도트 스킬 공격주기, 타수 설정 가능하게 변경

dpmModule/jobs/windBreaker.py
* fix #285
* 툴팁과 실제 동작이 다른것 반영
* 타겟수 증가 어빌리티를 계산식에 추가
=> fix: 윈드브레이커 천공의 노래 컴뱃 공식

dpmModule/character/characterKernel.py
=> fix: 소울웨폰 충전시 공+20

dpmModule/character/characterKernel.py
* 여제의 축복 전직업 패시브에 추가
* 연합의 의지 제로 제외한 전직업 패시브에 추가
* 도핑 목록에 영웅의 메아리 추가
fix #267
=> fix: 공용 0차 스킬 추가

dpmModule/jobs/archmageTc.py, dpmModule/jobs/bishop.py
* 비숍 언스로 발동된 힐의 최종뎀 효과 적용되게 수정
* 썬콜 썬브 히트 상수 분리
=> fix: 비숍, 썬콜

dpmModule/jobs/michael.py
* 로 아이아스 지속시간 165ms -> 165*1000ms
* 로 아이아스 최종뎀 증가량 수정
* 클라우 솔라스 딜레이 수정 (공속적용)
* 소드 오브 소울 라이트 시전 딜레이 수정 (공속적용)
* 소울 라이트 슬래시 딜레이 수정 (반올림->올림)
* 쿨감 받는 스킬들 적용
* 클라우 솔라스(소환)이 5초 후부터 공격하게 수정
* 오라 웨폰 발동시키는 스킬 목록 수정
=> fix: 미하일 스킬

dpmModule/jobs/viper.py
* 파이널 어택이 게이지 충전하지 않음 (1.2.316 패치)
* 스티뮬레이트 게이지 회복이 계속해서 발동되는것 수정
* 서펜트 스크류 초당 소모량 적용 안된것 수정
* 수정된 게이지 유지력을 반영해 딜사이클 변경
* 에너지 오브를 게이지 회복용으로만 사용
* 트랜스폼, 스티뮬레이트 둘 다 사용 가능하면 트랜스폼을 우선시함
* 스티뮬레이트는 완충 상태가 아니거나 게이지가 2000 이하일때 사용
=> fix: #361 실수 바로잡음

dpmModule/jobs/demonslayer.py
* 수동 서버러스를 어웨OFF일때만 사용
* 어웨ON일때는 포스 수급에 문제가 없음
* 리메인타임 상시 유지를 가정하지 않고 데몬 슬래시 이후 4초간 지속되게 함
* 신5차 추가시 키다운 도중 리메인타임이 풀리는 것을 반영하기 위함
* 딜사이클에 관련된 부분을 ConstraintElement에서 RuleSet으로 이동
=> fix: 데몬슬레이어 리메인타임, 딜사이클

dpmModule/jobs/demonslayer.py
=> fix: 데몬슬레이어 어웨이크닝에 슬래시 강화 패시브 적용안되게

dpmModule/jobs/evan.py
코드가 영 마음에 안드는데... 어떻게 해도 돌아와나 융합이 매끄럽게 구현이 안되네요.
일단 이대로 해두고 차차 개선하겠습니다.
=> fix: 에반 새로 만듬

dpmModule/jobs/demonslayer.py
=> fix: 데몬슬레이어 optimization_hint

dpmModule/jobs/windBreaker.py
* 최적화가 이상하게 되어서 오히려 딜이 하락하고 있었음
=> fix: 윈드브레이커 _use_critical_reinforce 플래그 제거

dpmModule/jobs/blaster.py
=> fix: 블래스터 발칸 펀치 타수

dpmModule/jobs/phantom.py, test/scheduler_test.py
=> Fix phantom function convention

dpmModule/jobs/cadena.py, dpmModule/jobs/pathfinder.py
=> fix: 패스파인더 블래스트 240ms

dpmModule/jobs/archmageFb.py, dpmModule/jobs/archmageTc.py, dpmModule/jobs/battlemage.py, dpmModule/jobs/bishop.py, dpmModule/jobs/evan.py, dpmModule/jobs/flamewizard.py, dpmModule/jobs/ilium.py, dpmModule/jobs/jobbranch/magicians.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/luminous.py
fix #422 
resolve #405 
fix #195
=> fix: 오버로드 마나 받는 스킬들만 적용

dpmModule/jobs/zero.py
* 조인트 어택에 알파 연계 누락된것 추가
* 조인트 어택 2타가 8타로 되어있던것 12타로 수정
* attackInfo에 있는 수치 기반으로 각 타격 딜레이 설정
* 조인트 어택 각 타격마다 오라웨폰 발동 가능
=> fix: 제로 조인트 어택

dpmModule/jobs/mechanic.py
=> fix: 메카닉 로봇 팩토리 최종뎀 롤백됨

dpmModule/jobs/pathfinder.py
* 디스차지 퍼뎀 타수 뒤바꿔씀, 맥뎀 안막히므로 dpm 차이는 없음
* 별 필요없는 아스트라 제한 제거
* 가이던스 게이지가 스택이 딱 1000일때도 발동이 되어야 함
=> fix: 패스파인더

dpmModule/jobs/mercedes.py
* 엘리멘탈 고스트 잔상확률 오류 수정
* 독립시행이 아님
* 엘리멘탈 고스트 잔상에 터지는 파이널 어택은 최종 데미지 감소가 없어야 함
* 유니콘 스파이크 코강당 2%가 아닌 3%
related #446
=> fix: 메르세데스 스킬

dpmModule/jobs/pathfinder.py
* http://www.inven.co.kr/board/maple/2299/5246733
=> fix: 패스파인더 블래스트 최종뎀 합적용

dpmModule/jobs/pathfinder.py
=> fix: 패스파인더 엣지 오브 레조넌스 최종뎀 합적용

dpmModule/jobs/demonslayer.py
=> fix: 데슬 서버러스에 블루 블러드 누락된것 추가

dpmModule/jobs/archmageFb.py
=> fix: 불독 익스플로전 딜레이

dpmModule/jobs/mechanic.py
=> fix: 메카닉 마그네틱 필드도 설치하도록 함

dpmModule/jobs/luminous.py
* 리버레이션 오브 추가 및 밸패 영향으로 비이퀄 앱킬을 쿨마다 박는게 더 강함
related #409
=> fix: 루미너스 딜사이클

dpmModule/jobs/mercedes.py
* 가이디드에 로얄 나이츠 발동됨
* 연계시 엘리멘탈 고스트의 잔상에 파택이 거의 전부 씹히는 오류
* 거스트 다이브가 착지지점이 정확히 겹치지 않으면 잔상이 터지지 않는 오류
=> fix: 메르세데스 스킬간 관계

dpmModule/jobs/adele.py, dpmModule/jobs/archmageFb.py, dpmModule/jobs/battlemage.py, dpmModule/jobs/bishop.py, dpmModule/jobs/blaster.py, dpmModule/jobs/darknight.py, dpmModule/jobs/flamewizard.py, dpmModule/jobs/ilium.py, dpmModule/jobs/kaiser.py, dpmModule/jobs/michael.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/pathfinder.py, dpmModule/jobs/phantom.py, dpmModule/jobs/soulmaster.py, dpmModule/jobs/zero.py
V skills from #50
related #408
fix #399
=> fix: 스킬 딜레이

dpmModule/jobs/angelicbuster.py
* 600ms가 아닌 660ms (클라값 870에 공속적용)
=> fix: 엔버 트리니티 퓨전 딜레이

dpmModule/jobs/hoyoung.py
=> fix: 호영 패시브

dpmModule/jobs/archmageFb.py
* 타수를 조정해서 계산하는 방법은 맥뎀에 막히지 않을때만 정확함
* 맥뎀에 막힐 경우를 고려해 초과시 최종뎀 감소된 데미지를 분리해서 계산
=> fix: 불독 도퍼노바 맥뎀 계산 정확하게 함

dpmModule/jobs/sniper.py
=> fix: 신궁 스플릿 디스턴싱 미적용 오류 반영

dpmModule/jobs/sniper.py
Reverts oleneyl/maplestory_dpm_calc#482
=> Revert "fix: 신궁 스플릿 디스턴싱 미적용 오류 반영"

dpmModule/jobs/evan.py
=> 임페리얼 브레스 퍼뎀 오타 수정

dpmModule/jobs/paladin.py, dpmModule/jobs/zero.py, dpmModule/kernel/core.py, dpmModule/util/extractMetadata.py
core의 passive skill list의 목록들은 `InformedCharacterModifier` 만을 반환해야 합니다. 이 부분을 추가로 수정했습니다.
=> Fix utilitiy not working

dpm_sheet.py
시뮬레이션 결과를 정렬한 후 엑셀파일로 자동으로 저장하는 코드입니다.
=> dpm 시뮬레이션 후 엑셀파일 자동 생성

.gitignore, dpm_sheet.py
* 패키지 없을 시 예외 발생시키고 프로그램 중단
* 결과물 `.gitignore`에 등록
=> 엑셀 스크립트 수정

dpmModule/jobs/jobutils.py
=> Use onJustAfter rather than onAfter

dpmModule/jobs/evan.py
* 마법 잔해 스택이 융합 스킬 타격중에만 쌓이도록 수정
* 드래곤 브레이크-돌아와! 스킬이 다오어 3타 위치에선 맞지 않는 것을 반영
* 조디악 레이를 고정 444타가 아닌 마력 충전 로직을 구현해 적용함
=> fix: 에반 스킬

dpmModule/jobs/globalSkill.py
처음에 코드 작성할때 쿨타임이 종료 후 90초인 걸로 알고 있어서 실수했던 것 같습니다.
=> 얄다바오트 쿨타임 오타수정

dpmModule/item/Genesis.py, dpmModule/jobs/jobutils.py
=> Genesis weapon

dpmModule/jobs/battlemage.py
배틀메이지의 블랙매직 알터,그림리퍼, 어비셜 라이트닝에 어둠 속성이 적용되지 않는 현상이 수정됩니다.
=> kms 1.2.340(배틀메이지)

dpmModule/jobs/jobbranch/bowmen.py, dpmModule/jobs/sniper.py
=> 신궁: 가이디드 애로우에 거리패시브 적용

dpmModule/jobs/ilium.py
=> 일리움 매서풀 공용코드 적용

dpmModule/jobs/adele.py, dpmModule/jobs/jobbranch/warriors.py, dpmModule/jobs/jobclass/flora.py
* chore: delete resolved todo
* feat: builder.add_trigger() can process periodic skills
=> fix(adele): aura weapon / full drive trigger list

dpmModule/jobs/__init__.py, dpmModule/jobs/demonavenger.py
평딜: 엑큐 사용, 실체 쿨마다 사용, 릴리즈 오버로드 발동 후 엑큐 스택 채워야함, 블피 사용여부 확인필요
극딜: 버프류 스킬 및 디멘션 소드 전부 사용 (재시전 여부 확인필요)
=> 데몬어벤져 (작업중)

dpmModule/jobs/jobutils.py
쿨감모: `CDR = jobutils.cdr_hat(4)`와 같이 사용가능
스탯% 감소는 1초부터 9초까지 각각 `[9, 12, 21, 30, 37, 40, 43, 50, 57]`입니다.
시드링: 리레, 리테, 크라이시스, 웨폰퍼프, 레벨퍼프, 링오브썸, 듀라빌리티, 크리데미지, 크리디펜스
웨폰퍼프, 레벨퍼프, 링오브썸은 해당 반지에 필요한 매개변수를 입력해야 합니다.
=> jobutils (쿨감모, 시드링, 리부트)

dpmModule/character/characterKernel.py, dpmModule/execution/rules.py, dpmModule/kernel/abstract.py, dpmModule/kernel/core.py, dpmModule/kernel/graph.py, dpmModule/kernel/policy.py
Union.get_card()의 리턴 형태를 (ExMDF,)에서 불필요한 wrapping 튜플을 제거하고 ExMDF로 변환
class ItemedCharacter 선언을 AbstractCharacter 바로 아래로 이동
사용되지 않는 parameter가 있는 경우 # TODO: 로 표시
사용하는 코드가 없어서 타입을 유추하지 못한 경우 typing이 없음
=> Add typing, cleanup (/kernel, /execution, characterKernel)

dpmModule/character/cdr.py, dpmModule/character/characterTemplateHigh.py, dpmModule/util/dpmgenerator.py, test.py
* works at ulevel >= 8000 only (legendary potential grade)
=> feat: cdr hat argument

dpmModule/jobs/eunwol.py
bool 값 변경만으로 약점간파 적용 여부를 쉽게 변경할 수 있도록 바꿨습니다.
=> 약점간파 적용 여부 상수화

dpmModule/jobs/striker.py
fix(striker): 신뇌합일 쿨타임
fix(striker): 신뇌합일 최종뎀 공식 (30레벨 기준 동일)
=> Fix striker

dpmModule/jobs/archmageFb.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/cadena.py, dpmModule/jobs/cannonshooter.py, dpmModule/jobs/dualblade.py, dpmModule/jobs/flamewizard.py, dpmModule/jobs/hero.py, dpmModule/jobs/hoyoung.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/nightwalker.py, dpmModule/jobs/paladin.py, dpmModule/jobs/shadower.py, dpmModule/jobs/windBreaker.py, dpmModule/jobs/zero.py, dpmModule/kernel/core/skill_wrapper.py
tick should not be updated when the
DotSkill is newly used during its duration.
=> fix: dot skill hit count

dpmModule/character/characterKernel.py, dpmModule/kernel/core/graph_element.py, dpmModule/kernel/core/result_object.py, dpmModule/kernel/core/skill.py, dpmModule/kernel/core/skill_wrapper.py
keep compatibility into 3.7 until pypy 3.8 release.
fix: elements from generate() could be None
=> pypy 3.7 compatibility

dpmModule/util/dpmgenerator.py, dpm_sheet.py
* refactor code
* add max damage loss
=> feat: enhanced dpm sheet generation

.flake8
from https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length
=> black-compatible flake8 config

dpmModule/jobs/blaster.py
=> fix(blaster): missing aura weapon trigger skills

dpmModule/character/linkSkill.py
=> refactor(character): 링크스킬 리팩토링

dpmModule/jobs/globalSkill.py
=> Genesis skill + globalSkill 정리 (재업)

dpmModule/jobs/demonavenger.py
* 데몬 프렌지 발동 타이밍을 강제로 앞당김
* 쓸만한 하이퍼 바디 추가
이외에는 텍스트 수정입니다.
=> 데몬어벤져 텍스트 수정, 프렌지 발동 타이밍 앞당김

dpmModule/jobs/bowmaster.py
* Magic Arrow does not trigger Mortal Blow
* Quibber Full Burst trigger Magic Arrow
* Arrow Rain, Optical Illusion, Mirror Break trigger Armor Break
* Armor Break cooltime reduce logic allows to decrease below 1000ms
* refactor: format bowmaster.py
=> fix(bowmaster): skill relationship

dpmModule/jobs/globalSkill.py
fixed remain & delay logic fits to actual game
=> fix: spider in mirror

dpmModule/character/characterKernel.py, dpmModule/jobs/ark.py, dpmModule/kernel/core/callback.py, dpmModule/kernel/core/skill_wrapper.py, test/scheduler_test.py
skill_modifier was required to build callback task
=> fix(callback): missing skill_modifier

dpmModule/jobs/nightlord.py, dpmModule/jobs/shadower.py
=> fix(nightlord, shadower): dark flare

dpmModule/jobs/bowmaster.py
* Quiver Barrage is affected by Armor Piercing
=> fix(bowmaster): Armor Piercing

dpmModule/jobs/kinesis.py
* Psychic Tornado should trigger Telekinesis
=> fix(kinesis): Telekinesis trigger

statistics.py
=> fix: apply preset.options to statistics.py

dpmModule/jobs/pathfinder.py
* using transition instead of combo assult gains more dpm
resolve #486
=> fix(pathfinder): update curse with transition

.github/workflows/lint_flake8.yml
Python Package -> Lint with flake8
=> ci: change action name

dpmModule/jobs/adele.py, dpmModule/jobs/angelicbuster.py, dpmModule/jobs/aran.py, dpmModule/jobs/archmageTc.py, dpmModule/jobs/ark.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/cadena.py, dpmModule/jobs/darknight.py, dpmModule/jobs/demonslayer.py, dpmModule/jobs/flamewizard.py, dpmModule/jobs/hero.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/mechanic.py, dpmModule/jobs/michael.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/nightwalker.py, dpmModule/jobs/paladin.py, dpmModule/jobs/shadower.py, dpmModule/jobs/zero.py
* Callback에 체이닝된 요소 있는지 점검할 것
* Callback의 딜레이가 0보다 큰 경우가 있는지 점검할 것
* 소울마스터
* 소울 이클립스 -> 솔루나 디바이드
* 호영
* 강림 괴력난신 -> 신들의 강림
* 미하일
* 라이트 오브 커리지 -> 용기의 빛 막타
* 키네시스
* 싸이킥 토네이도 막타
이 경우들은 일단은 기존처럼 처리해도 큰 문제는 없음... 롤백하거나 처리할 방법을 찾거나 해야함
* 팬텀
* 블랙잭 막타 -> 느와르 -> 저지먼트 스택
* 키네시스
* 싸이킥 토네이도 막타 -> 텔레키네시스
* 로 오브 그래비티(폭발) -> 텔레키네시스
* 카데나
* 서먼 스로잉 윙대거(폭발) -> 웨폰 버라이어티
* 서먼 릴리징 봄(폭발) -> 웨폰 버라이어티
* 아크
* 영원히 굶주리는 짐승 -> 다가오는 죽음
* 황홀한 구속 막타 -> 다가오는 죽음
=> Apply callback

dpmModule/jobs/archmageFb.py, dpmModule/jobs/blaster.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/cadena.py, dpmModule/jobs/globalSkill.py, dpmModule/jobs/ilium.py, dpmModule/jobs/kaiser.py, dpmModule/jobs/kinesis.py, dpmModule/jobs/luminous.py, dpmModule/jobs/mechanic.py, dpmModule/kernel/core/skill_wrapper.py
* _use, _useTick을 오버라이딩 하는 경우 super()을 반드시 호출하도록 함
* 딜레이, 데미지, 타수, modifier 계산은 다른 메소드에 위임
* 스택형 스킬을 표현하는 StackableDamageWrapper 추가
* 기존에 있는 StackDamageWrapper와 헷갈리는데 이름을 어떻게 할지...
* 역할이 겹치는 _result_object_cache와 _disabledResultObjectCache 통합
=> refactor: _use, _useTick inherit

dpmModule/jobs/windbreaker.py, dpmModule/kernel/core/skill_wrapper.py
* wind wall final damage is (50, 50, 50), not (100, 50, 50)
* howling gale is now stackable
=> fix(windbreaker): wind wall, howling gale

dpmModule/jobs/adele.py, dpmModule/jobs/angelicbuster.py, dpmModule/jobs/aran.py, dpmModule/jobs/ark.py, dpmModule/jobs/battlemage.py, dpmModule/jobs/bishop.py, dpmModule/jobs/bowmaster.py, dpmModule/jobs/cannonshooter.py, dpmModule/jobs/captain.py, dpmModule/jobs/darknight.py, dpmModule/jobs/dualblade.py, dpmModule/jobs/eunwol.py, dpmModule/jobs/evan.py, dpmModule/jobs/ilium.py, dpmModule/jobs/kaiser.py, dpmModule/jobs/luminous.py, dpmModule/jobs/mechanic.py, dpmModule/jobs/mercedes.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/nightwalker.py, dpmModule/jobs/paladin.py, dpmModule/jobs/phantom.py, dpmModule/jobs/shadower.py, dpmModule/jobs/sniper.py, dpmModule/jobs/striker.py, dpmModule/jobs/viper.py, dpmModule/jobs/wildhunter.py, dpmModule/jobs/windbreaker.py, dpmModule/jobs/zero.py
=> set optimize hint to all jobs

dpmModule/jobs/mercedes.py
While sylphidia is active, afterimage of elemental ghost does not appear.
Instead, final damage increases in proportion to the afterimage probability and damage ratio.
fix #588
=> fix(mercedes): Elemental ghost + Sylphidia

dpmModule/jobs/michael.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/phantom.py, statistics/preset.py
* 나로 스프 줄수
* 미하일 로얄가드 여부
* fix(phantom): blast dealcycle temporal fix
* need additional delay when blast-discharge combo is interrupted
=> Add options

dpmModule/jobs/archmageFb.py
=> fix(archmageFb): mist eruption procs meteor once

dpmModule/jobs/jobclass/adventurer.py, dpmModule/jobs/sniper.py
* damage is applied only to the skills which Mortal Blow is applied
* distance relative passives are applied to summon skill with 0 distance
reference: https://m.blog.naver.com/oe135/222092586856
=> fix(sniper): passive

dpmModule/execution/rules.py, dpmModule/jobs/windbreaker.py, dpmModule/kernel/core/skill_wrapper.py
* additional target by ability, core enhancement is not applied
* sync Soul Contract with Critical Reinforce
* stack Howling Gale when Critical Reinforce cooltime is under 30s
* optimize execution priority
fix #640
=> Fix windbreaker

dpmModule/jobs/cannonshooter.py
* BFG Cannonball is stackable
* sync Cannonball*3 with Soul Contract
* fix: Special Monkey Escort delay, remain time
* fix: Support Monkey Twins delay, hit, damage
* hit * damage is same as before the fix
=> Fix cannonshooter

dpmModule/item/ItemKernel.py, dpmModule/jobs/adele.py, dpmModule/jobs/angelicbuster.py, dpmModule/jobs/ark.py, dpmModule/jobs/cannonshooter.py, dpmModule/jobs/captain.py, dpmModule/jobs/eunwol.py, dpmModule/jobs/ilium.py, dpmModule/jobs/jobutils.py, dpmModule/jobs/mechanic.py, dpmModule/jobs/nightwalker.py, dpmModule/jobs/striker.py, dpmModule/jobs/viper.py, dpmModule/jobs/xenon.py
* add weapon_base_att field to Item class
* jobutils.get_weapon_att references chtr, no longer spec
=> fix: weapon base att reference

dpmModule/jobs/kinesis.py
* optimize execution priority
* keep pp >= 2 to prevent B.P.M turn off
* feat: add deal cycle, shot rate option
=> fix(kinesis): deal cycle

dpmModule/jobs/windbreaker.py
should be 5*3, mistake when removing wind wall(exceed)
=> fix(windbreaker): wind wall hit

dpm_sheet.py, statistics/preset.py
* max damage cap increased, remove damage loss column
* group by job before sort
=> feat: change dpm sheet generation format

statistics/batch.py, statistics/preset.py
* feat: batch run scripts
* fix: duplicate preset id
=> feat(statistics): batch script

dpmModule/jobs/michael.py
royal guard cancels skill delay
cancelling deadly charge each 15s will increase dpm
=> feat(michael): deadly charge - royal guard combo

dpmModule/jobs/adele.py, dpmModule/jobs/aran.py, dpmModule/jobs/zero.py
* 제로: 대검 마스터리
* 아델: 레조넌스
* 아란: 비욘더, 펜릴 크래시
카데나, 캡틴은 아직 확인 필요
=> 5차 강화의 타겟수 증가가 타겟수-데미지 교환에 영향을 주지 않음

.gitignore, statistics/detail_sheet.py
* 맥뎀 누수가 의미없어져서 제거
* 사용 횟수가 부정확한 경우가 많아 타수만 표기
* 마찬가지로 1회당 평균 데미지가 아닌 1타당 평균데미지를 표기하게 변경
=> feat: change detail_sheet format

dpmModule/jobs/michael.py
* cannot cancel deadly charge when USE_ROYAL_GUARD is false
* fix constraint
=> fix(michael): deadly charge cancel

dpmModule/jobs/jobclass/nova.py
=> fix: apply AS to pantheon

dpmModule/jobs/kinesis.py
* adjust UltimateTrain usage
* apply Train constraint to shot cycle
=> fix(kinesis): optimize dealcycle

dpmModule/jobs/kinesis.py
=> fix(kinesis): UltimateTrain delay

dpmModule/jobs/zero.py
* cdr is applied to time distortion, time holding
* remove whitespace before bracket in skill name
* fix AdvancedPowerStompTAG timing in alpha_legacy combo
* feat: add optional combo
=> fix(zero): cdr, dealcycle, skill name

dpmModule/jobs/ark.py
* 끝없는 고통 막타 타수분할 적용하면서 딜레이도 5배로 되었던것을 수정
* 끝없는 고통 막타 직후 게이지 빠지는것이 적용 안되던것을 수정
=> fix(ark): endless pain

dpmModule/jobs/dualblade.py
* 블레이드 토네이도(미러 이미징)의 타수가 원본보다 1회 많았던 것 수정
* 딜사이클 최적화
* 아수라가 블토카퓨의 발동 횟수를 방해하지 않도록, 사용 시점 및 키다운 시간 최적화
* 블레이드 스톰을 2회에 한번씩 얼닼사에 맞춰서 사용
* 메용2를 얼닼사에 맞춰서 사용
* 레투다와 엔버링크를 블레이드 스톰에 맞춰서 사용
=> fix(dualblade): BladeTornado, deal cycle

dpmModule/jobs/nightlord.py
* 얼티밋 다크 사이트 사용 시점 최적화
* 기본적으로 스프레드 스로우에 맞춰 사용
* 10초씩 밀리는것이 누적되어 시간이 안맞으면, 다음 스로우 블래스팅까지 대기
* 레투다, 소울 컨트랙트는 스로우 블래스팅에 맞춰 사용
=> fix(nightlord): deal cycle

dpmModule/jobs/mechanic.py
* despite the additional delay, dpm is higher with OpenGate
=> fix(mechanic): use OpenGate

dpmModule/jobs/ilium.py
fix #677 
컴뱃 제거시 딜 자체는 상승하나, 이것이 유효한 선택인지에 대해 일리움 유저들의 자문을 구할 필요가 있습니다.
=> 일리움 쓸컴뱃 제거 (draft)

dpmModule/jobs/angelicbuster.py, dpmModule/jobs/kaiser.py
* 엔젤릭버스터에 판테온 추가 (fix #643)
* 판테온 딜레이에 공속 반영되는것 적용
=> fix(nova): pantheon

dpmModule/jobs/captain.py
* 불릿 공격력을 직접 공격 스킬에만 적용
* 퀵 드로우 스택이 덜 쌓이는것, 종료하는 스킬이 아닌데도 종료되는것 수정
=> fix(captain): apply bullet, fix QuickDraw

dpmModule/jobs/nightlord.py, dpmModule/jobs/nightwalker.py
* 표창을 사용하는 스킬에 표창 공격력 적용
fix #396
=> fix(nightlord, nightwalker): apply javelin

dpmModule/jobs/cadena.py
https://github.com/Monolith11/memo/issues/117#issuecomment-753744202
오늘 측정한 자료를 바탕으로 수정본을 올립니다.
=> 카데나 니들배트의 5차 강화의 타겟수 증가가 데미지% 증가에 영향을 주지 않음

dpmModule/jobs/pathfinder.py
http://www.inven.co.kr/board/maple/2296/17599
다수타겟 효과는 블래스트에 적용되지 않는다고 합니다.
이것만 해결되면 타겟수 뎀증 이슈는 전부 해결되는 것 같습니다.
=> 패스파인더 flake8 수정

dpmModule/jobs/pathfinder.py
=> fix(pathfinder): Ancient Archery boss_pdamage

dpmModule/jobs/hoyoung.py
* sync Soul Contract and Ready To Die to 천지인 환영
* so that it is used with 극대 분신난무
=> fix(hoyoung): deal cycle

dpmModule/jobs/kain.py
* SneakySnipingRelease get both breath shooter, execution hyper
* ThanatosDescentArrow should not activate when ThanatosDescent is off
* fix optimization hint
=> fix(kain): SneakySniping, ThanatosDescent

dpmModule/jobs/kain.py
* sync CriticalReinforce to ThanatosDescent
* MaliceTick should be onTick, not onAfter
=> fix(kain): deal cycle, malice gain

dpmModule/jobs/kain.py
* add missing final damage to ChainSickleFinal, PoisonNeedleSpin
* use StrikeArrowRelease when Malice is 500
* use PhantomBlade when DeathBlessingStack >= 9
=> fix(kain): Execution final damage, deal cycle

dpmModule/jobs/kain.py
* optimize hyper passive
* fix sneaky sniping cooltime
* optimize skill priority
=> fix(kain): hyper, sneaky sniping, deal cycle

dpmModule/kernel/core/skill_wrapper.py
* fixed an error in resetting cooldown when the stack is filled
=> fix(core): stackable skill cooltime

dpmModule/jobs/mechanic.py
* apply combat, ability to MetalArmorExtreme
* optimize skill priority
=> fix(mechanic): passive, skill priority 

dpmModule/jobs/kain.py
=> fix(kain): skill delay, priority

dpmModule/jobs/pathfinder.py
* sync SoulContract to CriticalReinforce
=> fix(pathfinder): deal cycle

dpmModule/jobs/phantom.py
* 얼티밋 드라이브에 선딜이 없고 후딜만 있는것 반영
* 템페스트 오브 카드를 딜사이클에 포함 (쿨감 4초 기준으로 최적화)
=> Fix phantom

dpmModule/util/dpmgenerator.py, statistics/base_stat.py, statistics/detail_sheet.py, statistics/graph.py, statistics/peak.py, statistics/saver.py, test.py
* add damage flow graph
* add average base stat calculation (boss_pdamage, armor_ignore, patt, crit_damage, att, stat_main)
* add damage peak graph
=> add various statistics script

dpmModule/character/characterTemplate.py, dpmModule/gear/GearBuilder.py, dpmModule/gear/SetItem.py
* amazing scroll was not applied by mistake
* removed incPDD in amazing scroll (unnecessary for dpm)
=> fix(gear): amazing scroll

dpmModule/character/configs/8500.yaml
* add stat_sub, stat_sub2 for acc_upgrade
* add Arcs authentic symbol
* change weapon/subweapon/emblem add_potential to patt 30
* use black heart
* fix: change DA, Xenon hat to CRA set
=> fix(character): 8500 template

dpmModule/character/characterKernel.py, dpmModule/jobs/jobutils.py
* used for WeaponPuff seedring calculation
=> feat: get_weapon_total_att

dpmModule/character/doping.py
* 길드의 축복 -> 길드의 더 큰 축복
* 붕어빵 뿌리기 추가
* 유니온의 힘 추가
=> fix(character): add doping list

statistics/base_stat.py, statistics/moving_total.py
* feat(statistics): add base_stat arguments
* refactor(statistics): rename peak -> moving_total
=> statistics changes

dpmModule/character/hyperStat.py
* modifying Hyperstat.enhancement causes multithreading memory pollution
=> fix: do not modify Hyperstat.enhancement

dpmModule/jobs/kinesis.py
* for shot cycle, use Ultimate-Material while Psychic Over
=> fix(kinesis): shot cycle skill rotation

dpmModule/jobs/soulmaster.py
* Dance of Moon(air) delay is 330 in 2AS
=> fix(soulmaster): speeding dance delay

dpmModule/jobs/globalSkill.py
* 제네시스 스킬 코드가 캐릭터의 무기 이름에 대응하도록 설정
* 제네시스 스킬이 쿨감을 받도록 설정
각 직업 코드에 제네시스 스킬을 적용하는 건 conf 변환 완료 후에 작업하겠습니다.
=> 제네시스 무기 스킬 작동하도록 설정

dpmModule/character/configs/8500-reboot.yaml, dpmModule/character/configs/8500.yaml, dpmModule/gear/Gear.py
* 8500급에 방패 사용
* Gear에서 `pdamage_indep`를 인식하지 못하는 오류 수정
=> Modified 8500 & fixed Gear error

dpmModule/jobs/flamewizard.py
* cdr is applied to burning region
* optimize skill priority
* sync Infinity Flame Circle to Burning Region
=> Fix flamewizard

dpmModule/jobs/bowmaster.py
* prepare action of Hurricane does not affect hit count
=> fix(bowmaster): remove Hurricane prepare delay

dpmModule/jobs/striker.py
* AS is applied to 교아탄
* remove incorrect skills in Lightning stack increasing list
=> fix(striker): 교아탄 delay, Lightning stack

dpmModule/jobs/adele.py
* final damage of Resonance is additive
* sync Grandis Goddess Bless to Infinite
=> fix(adele): skill info, deal cycle

dpmModule/character/weaponPotential.py, dpmModule/jobs/angelicbuster.py, dpmModule/jobs/archmageTc.py, dpmModule/jobs/ilium.py
* greedy method sometimes chooses a potential that is not optimal
=> feat: brute force weapon potential optimization

dpmModule/jobs/michael.py
=> hotfix: 클라우 솔라스 소환 스킬퍼뎀

dpmModule/jobs/flamewizard.py
* use BlazingExtinction each 9 hit
=> fix(flamewizard): deal cycle

dpmModule/jobs/xenon.py
* fix condition to fire only at maximum aim
* each PhotonRayHit triggers Triangulation
=> fix(xenon): Photon Ray

dpmModule/jobs/zero.py, statistics/preset.py
=> Zero combos

dpmModule/jobs/bowmaster.py, dpmModule/jobs/eunwol.py, dpmModule/jobs/luminous.py, dpmModule/jobs/mercedes.py, dpmModule/jobs/michael.py, dpmModule/jobs/nightlord.py, dpmModule/jobs/viper.py, dpmModule/jobs/wildhunter.py, dpmModule/jobs/xenon.py, dpmModule/jobs/zero.py, statistics/preset.py
=> feat: kms 1.2.347

dpmModule/jobs/battlemage.py, dpmModule/jobs/ilium.py, dpmModule/jobs/luminous.py, dpmModule/jobs/michael.py, dpmModule/jobs/pathfinder.py, dpmModule/jobs/striker.py, dpmModule/jobs/viper.py, dpmModule/jobs/windbreaker.py
=> update: kms 1.2.349

dpmModule/jobs/windbreaker.py
* EmeraldFlower armor_ignore applies to boss after patch
=> fix(windbreaker): kms 1.2.349 EmeraldFlower

dpmModule/jobs/xenon.py
=> KMST 1.2.124 추가수정

dpmModule/jobs/windbreaker.py
* 61hit is available due to VortexSphere changes
=> fix(windbreaker): HowlingGail hit count
