oleneyl/maplestory_dpm_calc

- dpmModule/jobs/demonavenger.py
- dpmModule/jobs/shadower.py
데벤져 (아직 딜사이클, 5차강화순서 미작성)
1. 어빌리티 변경 (재사용, 크확, 보공)
2. 단계별 엑스큐션, 프렌지 장판, 블피, 디멘션소드 추가
섀도어
1. 쉐파 적용 (듀블 코드 복붙)
2. 암살 스택 확률 70% / 95%로 변경 ([스킨헤드](https://maple.gg/u/%EC%8A%A4%ED%82%A8%ED%97%A4%EB%93%9C)님 제보)
> 데몬어벤져, 섀도어 변경사항

- dpmModule/jobs/angelicbuster.py
- dpmModule/jobs/cadena.py
- dpmModule/jobs/shadower.py
- dpmModule/jobs/striker.py
- dpmModule/jobs/zero.py
- full_test.py
스커는 지난번 천지개벽 패치를 적용하고 그에 따라 딜사이클을 수정했습니다.
연계 100% 가정으로 천지개벽이 켜져 있을때 태풍과 섬멸을 반복하며 꺼져 있을 때는 벽력과 섬멸을 반복합니다.
제로는 대검 마스터리가 올바르게 작동하도록 수정했습니다. (타겟수 1마리 감소할때마다 데미지 8% 증가) 리밋브, 조택이 베타일때 발동하는 걸로 가정하고 작성했습니다. 제로는 이거 말고도 고칠 게 엄청 많은 편이라 나중에 시간나면 정리해서 올리겠습니다.
두 직업 모두 유의미한 딜 상승이 확인되었으나, 제가 볼 수 있는 건 결과값뿐이므로 제작자분께서 사이클이 돌아가는지 한번 더 확인해주셔야 할 것 같습니다...
> 스트라이커, 제로 수정

- dpmModule/jobs/nightlord.py
* 스프레드 스로우 도중 풍마수리검 사용
* 마크 오브 나이트로드 사출 확률 37.5%
* 페이탈 베놈 도트뎀 적용
* 퍼지 에이리어 - 보스 킬러 하이퍼 적용
* 다크로드의 비전서 막타 퍼뎀 수정
* 다크로드의 비전서에는 마크 사출 안됨
* 스프레드 추가 줄기 15타 각각에 마크 판정이 들어감
> 나이트로드 스킬 수정

- dpmModule/jobs/nightlord.py
* 쿼드에 마크 터질 확률 37.5%인데 35%로 기입했던 것 수정
* 풍마수리검의 마크 발동 확률 실험결과 반영
> 마크 오브 나이트로드 발동 확률 수정

- dpmModule/jobs/dualblade.py
- dpmModule/jobs/jobbranch/thieves.py
https://github.com/oleneyl/maplestory_dpm_calc/issues/104
* 블토 1+6타 -> 1+5타
* 파컷 버프가 노쿨로 직접 발동되던것 수정
* 파컷 버프에 벞지 적용 안되는 현상 수정
* 팬블 하이퍼 방무 합연산 -> 곱연산
* 파컷 이후 써레 1번만 사용
> 듀얼블레이드 스킬 수정

- dpmModule/jobs/zero.py
* 무기상수 등 제대로 적용 안된 부분이 있었음
* 변경하는 김에 보기 편하게 수정
베타에도 크바로 인한 크뎀 보정이 들어가있는데, 제가 알기로는 크바 상태의 적을 알파가 타격시 크뎀 20% 추가입니다.
다른 이유가 있어 적어둔거라면 돌려놓도록 하겠습니다.
https://github.com/oleneyl/maplestory_dpm_calc/issues/158
> fix: 베타 상태의 스탯 변화

- dpmModule/jobs/nightwalker.py
https://github.com/oleneyl/maplestory_dpm_calc/issues/142
* 쉐도우 서번트 익스텐드 쿨타임 수정
* 쉐도우 바이트 버프가 타격 2초 후 발동
> 나이트워커 스킬 수정

- dpmModule/item/Absolab.py
- dpmModule/item/Arcane.py
- dpmModule/item/Default.py
- dpmModule/item/ItemKernel.py
- dpmModule/item/RootAbyss.py
* 기존에는 getWeapon 클래스를 블레이드 가져오는데 다시 활용해서, self.modifier가 블레이드에도 적용되고 있었음
* self.modifier에는 무기의 기본옵이 들어가는데, 여기에 있는 주스탯 방무 보공이 블레이드에도 다시 적용되고 있었음
* getBlade() 메소드를 분리해 블레이드 기본옵만 들어가도록 처리함
* 아케인/앱솔/카룻 여부를 알 수 없어 단순히 modifier 값으로 비교하는데, 주의 필요
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/153
> fix: 듀얼블레이드 보조무기에 방무보공 안들어가게

- dpmModule/character/characterKernel.py
* 향상된 10단계 주스탯 물약 사용
* 길드스킬 개편 적용 (60포)
* 고보킬 고관비 동시복용 안되므로 고보킬->반빨별 이름수정
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/153
> fix: 도핑 최신화

- dpmModule/jobs/demonslayer.py
* 데몬 슬레시 딜레이 수정
* 불필요하게 두번 선언된 코드 정리
* 데빌 크라이 디버프에 있는 방무 적용
* 어웨이크닝 OFF일때 크라이 사용 안하도록
* 스킬들의 추가 보공과 점유율 고려해 optimization_hint 변경
* 추가타 이름 추가
* 리메인타임 리인포스 적용
* 메타모포시스 구체에 벞지 적용
* 메타모포시스에 블루 블러드 적용
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/178
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/131
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/171
> fix: 데몬슬레이어 스킬

- dpmModule/jobs/archmageTc.py
- dpmModule/jobs/ark.py
- dpmModule/jobs/bishop.py
- dpmModule/jobs/cadena.py
- dpmModule/jobs/hero.py
- dpmModule/jobs/jobclass/heroes.py
- dpmModule/jobs/kaiser.py
- dpmModule/jobs/luminous.py
- dpmModule/jobs/shadower.py
- dpmModule/jobs/viper.py
- dpmModule/jobs/wildhunter.py
- dpmModule/kernel/core.py
* 기존에는 Skill 각각이 퍼뎀\*타수를 계산해두고 상위 모듈로 (퍼뎀\*타수, 타수)를 전달하고 있었음
* 이런 구조가 데미지 계산 부분을 해석하는데 혼란을 준다고 판단해 리팩토링을 진행
* Skill과 SkillWrapper는 (퍼뎀, 타수)만 전달하고, 계산은 calculate_damage에 일임함
* ResultObject의 hit이 default 1로 되어있는것이 위험하다고 판단, 필수 parameter로 변경
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/202
> refactor: 퍼뎀*타수를 calculate_damage로 이동

- dpmModule/jobs/striker.py
스커 패시브에 연계시 최종뎀 20%가 있는데 이게 벽력 섬멸 교아탄에만 적용되고 태풍에 빠져있었습니다.
태풍에 코강이 적용중인지에 대한 질문이 있었는데, 적용중인것 같으나 한번 확인 부탁드립니다.
* 적용중입니다.
> 스트라이커 태풍 연계시 최종뎀 20% 반영

- dpmModule/jobs/cannonshooter.py
- dpmModule/jobs/jobclass/adventurer.py
* BFG 캐논볼의 충돌 횟수를 허수아비 기준으로 조정
* ICBM의 폭발 타격 횟수를 4회로 조정
* 파이렛 플래그의 주스탯 증가가 스탯%를 받도록 함
* 로디드 다이스의 평균 증가량 수정
* 벅샷 더미 버프 추가
> fix: 캐슈 스킬

- dpmModule/jobs/kinesis.py
실측 기반으로 일괄 수정
* 싸이킥 드레인 시전딜레이, 공격주기 수정
* 싸이킥 그랩 공격주기 수정, 그랩으로 인한 지연 고려
* 불릿 딜레이 수정, 그랩으로 인한 지연 고려
* 얼티메이트-트레인 딜레이, 공격 횟수 수정
* BPM 공격주기 수정
* 싸이킥 오버 pp 차오르는 주기 수정
* 싸이킥 토네이도 딜레이 수정
* 싸이킥 토네이도 막타 타수 수정
* 싸이킥 토네이도 폭발이 20초 후 이뤄지도록 함
* 무빙매터 딜레이 수정
* 텔레키네시스 코강당 3% 증가로 수정
* 얼티메이트-BPM, 트레인에 크뎀 20퍼 빠진것 수정
* 싸이킥 오버 상태에서의 메테리얼 pp소모 수정
* 싸이킥 오버 상태에서의 얼티메이트 스킬 사용 가능 여부 정확하게 판정
* pp 변동은 스킬의 딜레이가 끝난 후가 아닌 스킬 사용 시점이므로, onBefore으로 일괄 변경
* 싸이킥 차지의 충전량 정확하게 변경
* 샷을 아예 안쓰고 메테리얼만 쓰는게 더 셈
* 트레인은 싸이킥 오버가 아닐때도 계속해서 쓰는게 더 셈
* 트레인을 곧 써야하면 메테리얼 안쓰고 기다림
* 패시브 이름 수정
* 에버싸이킥 코드와 다른 주석 제거
> 키네시스 스킬 수정

- dpmModule/kernel/core.py
* calculate_damage에 AbstractSkill의 spec을 전달
* spec이 dot라면 최종뎀, 뎀퍼를 0으로 적용
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/212
@oleneyl 이런 식으로 변경해도 되는건지 확인 부탁드립니다.
> feat: 도트 스킬에 뎀퍼, 최종뎀 적용 안되게 함

- dpmModule/jobs/jobbranch/bowmen.py
- dpmModule/jobs/jobbranch/pirates.py
- dpmModule/jobs/jobbranch/thieves.py
- dpmModule/jobs/jobbranch/warriors.py
- dpmModule/jobs/jobclass/cygnus.py
- dpmModule/jobs/nightwalker.py
- dpmModule/jobs/soulmaster.py
- dpmModule/jobs/striker.py
- dpmModule/jobs/windBreaker.py
* 엘리멘탈: 다크니스 딜레이 1440 -> 900
* 쉐도우 서번트 딜레이 0 (펫버프)
* 쉐도우 배트 퍼뎀 590 -> 620
* 쉐도우 일루전 딜레이 990 -> 690
* 도미니언 딜레이 2680 -> 1890
* 쉐도우 스피어 쿨타임 버림 적용
* 쉐도우 스피어 거대 창 30렙 퍼뎀 1360 -> 880
* 쉐도우 바이트 딜레이 810 -> 630
* 레디 투 다이 딜레이 780 -> 1200 (2단계)
* 스톰 브링어 660 -> 0
* 핀포인트 피어스 900 -> 690
* 시그너스 팔랑크스 780 -> 600
* 하울링 게일 780 -> 630
* 크리티컬 리인포스 780 -> 600
* 셀레스티얼 댄스 700 -> 570
* 오라 웨폰 0 -> 720
* 연계 도중 팔랑크스 방향전환 가능, 타수 100% 적용
* 하이퍼 벽력-리인포스 대신 섬멸-이그노어 가드 사용
* 신뇌합일 딜레이 0 -> 540
* 오버드라이브 딜레이 540 -> 420
플위는 다른 pr에서 수정
> fix: 시그너스 직업 스킬

- dpmModule/jobs/mechanic.py
* 로봇 마스터리 최종뎀 수치를 깔끔하게 정리했습니다.
* 레지스탕스 라인 인팬트리가 공용 코드를 사용하도록 변경했습니다.
테스트 결과 변경 전과 동일한 수치가 나옵니다.
> 메카닉 로봇 마스터리 상수 정의, 공용코드 적용

- dpmModule/jobs/shadower.py
* 소블 7\*2\*20타에서 7\*2\*15타로 수정
* 배오섀 14타로 적용, 소환 스킬로 변경
* 암살 2타 딜레이 클라와 맞게 변경
* 얼닼사 최종뎀이 어닼사와 합연산 정확히 되도록 함
* 소닉 블로우가 준비 딜레이를 포함해 2.5초가 되도록 조정
* docstring 현 로직과 동일하게 수정
* 픽파킷 개수 스킬 타수와 쉐파 고려해 정확히 적용
* 프리마 크리티컬의 크확을 생각해 크확100 안맞추는 경우는 없을 것이므로 크확 제거
* 배오섀 시전 딜레이 수정 (공속 영향 안받음)
* 딜사이클에 다크 플레어 추가
* 쉐파는 펫버프로 사용, 인스팅트는 직접 발동
* 배오섀, 연막탄은 닼사를 이어서 사용하므로 닼사 딜레이 합산
* 메익 퍼뎀이 그리드 패시브로 인해 120%*2로 되는것 반영
* 다크 사이트 딜레이 120ms로 수정
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/170
> fix: 섀도어 스킬

- dpmModule/jobs/archmageTc.py
- dpmModule/kernel/core.py
* 빙결 중첩을 단순 스택형 스킬로 전환
* 모든 중첩 변동을 onAfter으로 변경
* 체라, 블리자드 컴뱃 수치 수정
* 아이스 에이지 장판 제대로 동작하게 함
* 더이상 안쓰는 EjaculateSkill 제거
* 프로즌 오브 4초간 19타로 변경
* 프로즌 오브 퍼뎀 200 -> 220
* 프로즌 오브 쿨마다 사용하게 변경
* 스오스 퍼뎀 700+40*레벨 -> 850+34*레벨
* 스오스 처음에만 스택+3 -> 틱마다 스택+3
* 라스피 32회 반복 -> 30회 반복
* 아이스 에이지 공격에 블리자드 추가타 발동
* 딜레이
* 썬브 770 -> 1080
* 엘퀴네스 900 -> 600
* 오브 390 -> 690
* 라스피(단일) 250 -> 270
* 라스피(막타) 0 -> 1080
* 아이스 에이지 870 -> 660
> fix: 썬콜 스킬

- dpmModule/jobs/angelicbuster.py
- dpmModule/jobs/demonslayer.py
- dpmModule/jobs/dualblade.py
- dpmModule/jobs/eunwol.py
- dpmModule/jobs/hero.py
- dpmModule/jobs/ilium.py
- dpmModule/jobs/kinesis.py
- dpmModule/jobs/mechanic.py
- dpmModule/jobs/nightlord.py
- dpmModule/jobs/phantom.py
- dpmModule/jobs/sniper.py
* 귀참 딜레이 600 -> 630
* 분혼 딜레이 900 -> 810
* 진귀참 딜레이 720 -> 540
* 파쇄철조-회 딜레이 90 -> 360
* 봄버 타임 딜레이 990 -> 900
* 전탄발사 시전/버프/하차 딜레이 수정
* 전탄발사 페널티 적용 시점 수정
* 전탄발사 11\*37타 -> 11\*49타
* 트리니티
* 1, 2타 470 -> 360
* 3타 130 -> 360
* 마스코트 패밀리어 1080 -> 810 (공속 적용됨)
* 부스터 펫버프화
* 데빌 크라이 1620 -> 1260 (1650에 공속적용)
* 서버러스 900 -> 690 (공속 적용)
* 오르트로스 1000 -> 510 (클라 490, 30단위 올림)
* 메타모포시스 공격주기 500 -> 510
* 써든레이드 900 -> 690
* 파컷 870 -> 450 (기본 150+경직300)
* 플래시 뱅 600 -> 390
* 아수라 선딜 810ms 추가
* 아수라 후딜 360ms 추가
* 블레이드 스톰 첫타 660 -> 120
* 블레이드 스톰 후딜 120ms 추가
* 카르마 퓨리 990 -> 750 (공속적용)
* 블레이드 토네이도 720 -> 540 (공속적용)
* 발할라 840 -> 900
* 콤보 데스폴트 1680 -> 1260 (공속적용)
* 콤보 인스팅트 450 -> 360 (공속적용)
* 패스트 차지 600 -> 30 (클라값)
* 크래프트:롱기누스 1053 -> 780 (600+연계취소)
* 그람홀더 900 -> 0 (클라에 딜레이 없음)
* 소오크 660 -> 510*2 (공속적용, 2회시전)
* 오래되어 …
> 많은 직업들 딜레이 수정

- dpmModule/jobs/paladin.py
* 두손둔기 착용 기준 엑스퍼트 적용
* 위협 딜레이 확률반영
* 엘리멘탈 포스 펫버프로
* 홀리 유니티 최종뎀 소수점 버림
* 라이트닝 차지, 디바인 차지 딜레이 공속적용
* 라이트닝 차지, 디바인 차지 타수 수정(어드밴스드 차지 적용)
* 라이트닝 차지, 디바인 차지 사용 주기에 벞지 고려함
* 딜사이클에 생츄어리 추가
* 블래스트-크리티컬 레이트 안씀
* 블래스드 해머 액티브 효과 제대로 구현
* 블레스드 해머 액티브 시전 딜레이 추가
* 그랜드 크로스 기본/강화 각각 타수와 지속시간 전분 기반 적용
* 그랜드 크로스 시전/종료 딜레이 적용
* 그랜드 크로스 방무 100이 크뎀 100으로 되어있던것 수정
* 5차 스킬들에 메르쿨감 적용
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/182
> fix: 팔라딘 스킬

- dpmModule/jobs/darknight.py
* 일반 궁그닐이 새크리/리인카때 시전 안되도록 함
* 무한 궁그닐, 다크 임페일이 오라 웨폰 발동 가능하게 함
* 피어스 사이클론에 메르쿨감 적용
* 다크 스피어 딜레이에 공속반영
* 하이퍼 변경: 비홀더-버프 리인포스 -> 리인카네이션-데미지
* 새크리파이스, 궁그닐 고려한 optimization_hint 추가
* 비홀더 쇼크에 패시브로 강화되는 퍼뎀 300%p 추가
* 궁그닐 디센트의 하이퍼 방무 곱적용으로 변경
* 피어스 사이클론 22회 -> 25회
* 비홀더 임팩트 공격주기, 딜레이 변경 (확정됨)
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/242
> fix: 다크나이트 스킬

- dpmModule/jobs/bowmaster.py
- dpmModule/jobs/jobbranch/bowmen.py
* 샤프 아이즈, 일루젼 스텝 사용하지 않던것 수정
* 샤프 아이즈 딜레이 다른 궁수와 통일
* 애로우 플래터 공격주기 210ms
* 이볼브 끝나면 피닉스 자동으로 나오므로, 피닉스 딜레이 제거
* 모탈 블로우가 적용되는 스킬에만 뎀퍼 적용
* 어드밴스드 퀴버가 발동하는 스킬을 정확히 반영
* 아머 피어싱의 컴뱃 수치 입력
* 아머 피어싱을 폭풍의 시, 가이디드 애로우에만 적용
* 폭풍의 시 선딜 적용
* 샤프 아이즈 하이퍼 적용
* 애로우 플래터가 폭풍의 시-리인포스 받는것 적용
* 윈드 오브 프레이 스킬 생성
* 딜사이클에 들어가진 않음
* 5차 스킬들에 메르쿨감 적용
* 애로우 레인의 마법 화살 확률 2배 적용
* 애로우 레인 시전 딜레이 720 -> 810
* 애로우 레인 공격주기 1.2.332 패치 기준으로 변경
* 애로우 레인은 파이널 어택 발동 안되는것 검증됨, 코드에 적용
* 퀴버 풀버스트의 공퍼가 과도하게 적용된것 수정
* 퀴버 풀버스트가 버프->공격 순으로 사용되게 함
* 퀴버 풀버스트의 불화살 공격주기를 총 90타가 나오게 수정 (기존 60타)
* 퀴버 풀버스트의 독화살 데미지가 안들어가던것 수정
* 독화살에 중독된 적은 크뎀+8%, 퀴버 풀버스트의 효과로 취급하는 것으로 적용해둠
* 잔영의 시 액티브/패시브 분리, 퍼뎀 타수 수정
* 잔영의 시 액티브가 12회 공격하던것 14회로 수정
* 잔영의 시 패시브를 적당한 주기의 소환수로 취급, 약 3~4회 공격
* 가이디드 애로우가 마법 화살을 발동함
* 90초 쿨인 프리퍼레이션, 엔버링크를 120초 주기에 맞춰 사용 …
> fix: 보우마스터 스킬

- dpmModule/jobs/windBreaker.py
쓸컴뱃 사용 시 천공의 노래 타겟수에 따른 추가 데미지가 20%에서 21%로 증가하여 하이퍼 포함 총 추가 데미지는 127.36%에서 134.358881%로 증가하는 점을 반영했습니다.
모든 스킬에 쓸컴뱃 수치를 반영했습니다.
일정하지 않은 formatting을 일부 수정했습니다.
> 윈드브레이커 쓸만한 컴뱃 오더스 반영

- dpmModule/jobs/adele.py
- dpmModule/jobs/jobclass/flora.py
- dpmModule/kernel/core.py
* 특정 스킬의 스택을 참조해 타수가 변동되는 StackDamageSkillWrapper 도입
* 에테르 게이지 구현, 평균으로 적용하던 스킬들 전부 변경
* 오더스 수치 입력 (아직 사용 x)
* 쿨감 적용
* 사용시 에테르 게이지 소모, 지속시간 40초 구현
* 에테르 게이지를 실시간으로 반영해 타수 변동됨
* 블로섬의 딜레이가 공속 영향 안받는것 확인, 420ms로 변경
* 블로섬 1개는 데미지 100% 들어가는것 반영
* 게더링, 블로섬 데미지가 오더 개수를 실시간으로 반영, 80% 히트 가정함
* 게더링-디바이드-블로섬 순서로 사용하도록 함
* 게더링-블로섬 도중 오더 공격하지 않게 함
* 게더링-블로섬 도중 오더 잔여시간이 바뀌지 않게 함
* 테리토리 막타가 시작이 아닌 끝날때 터지게 함
* 마커가 생성/파쇄 각각 공격하는것 반영
* 인피니트 공격주기, 타수 전분에 맞춤
* 크리에이션을 SummonSkill이 아닌 디바이드 이후 조건부로 사용되는 DamageSkill로 변경
* 샤드를 크리에이션과 같이 트리거 스킬에 반응하는 공격으로 변경
* 매직 서킷 풀드라이브의 마력 폭풍을 오라 웨폰과 같은 로직으로 변경
* 그레이브 쿨마다 사용하도록 변경
* 스콜 딜사이클에 추가
fix #119 
fix #252 
fix #253
> fix: 아델 스킬

- dpmModule/jobs/bowmaster.py
- dpmModule/jobs/jobclass/heroes.py
- dpmModule/kernel/core.py
* AbstractSkillWrapper에 calculate_cooltime 추가해서 사용
* 여러 엣지 케이스 (5초, 10초, 12초 등)에 대해 테스트 완료
* 보우마스터의 아머 피어싱에 쿨감 적용
> feat: 쿨타임 고정 감소 로직 적용

- dpmModule/jobs/bishop.py
- dpmModule/jobs/blaster.py
- dpmModule/jobs/eunwol.py
- dpmModule/jobs/luminous.py
- dpmModule/jobs/shadower.py
- dpmModule/jobs/wildhunter.py
- dpmModule/kernel/core.py
- dpmModule/util/dpmgenerator.py
- test.py
fix https://github.com/oleneyl/maplestory_dpm_calc/issues/102
* calculation_process 로그에 Spec을 함께 표시
* 소환 스킬의 Damage가 0일때 summon인지, graph control인지 구분이 필요했음
* 무의미한 Use가 statistics에 포함되지 않게 함
* 스킬의 사용횟수, 타수, 데미지를 모두 표시
* 소환수의 소환 횟수와 공격 횟수 따로 표시
* 버프, 공격, 소환 스킬 순서대로 표시, 각 범주 내에서 이름순 정렬해서 표시
* test.py에 --stat 플래그 추가, 점유율만 보고 싶을때 사용
결과 예시
> feat: 로그 과정 개선

- dpmModule/kernel/core.py
여는 괄호 ( 으로 스킬명을 split해서 같은 이름인 경우 합쳐지게 하고, 점유율 순으로 정렬합니다.
스킬명을 작성할 때 점유율이 합쳐져서 나오게 하고 싶은 경우 괄호 앞의 스킬 이름이 똑같아야 합니다.
ex)
암살 1타, 암살 2타 (x)
암살(1타), 암살(2타) (o)
블레이드 토네이도, 블레이드토네이도(소환) (x)
블레이드 토네이도, 블레이드 토네이도(소환) (o)
이 점에 유의해야 합니다.
> feat: statistics에 스킬별 통합 점유율 표시

- dpmModule/jobs/archmageFb.py
- dpmModule/jobs/archmageTc.py
- dpmModule/jobs/bishop.py
- dpmModule/jobs/jobclass/adventurer.py
- dpmModule/jobs/wildhunter.py
- dpmModule/kernel/core.py
* 프레이가 사용 시점의 주스탯을 따라 최종뎀이 적용되게 함
* 고정 스탯이 계산에 빠져있던 버그 함께 해결함
* 전 스킬 컴뱃/패시브 레벨 수치 입력
* 인피니티에 컴뱃 적용, 모험가 법사도 일부 변경
* 벤전스 엔젤레이 방깎 적용
* 피스메이커 3히트 기준으로 변경
* 헤븐즈도어 딜레이 수정, 딜사이클에 추가
* 엔젤 오브 리브라 공격주기 수정
* 소환수 표식 매커니즘 변경
* DamageSkillWrapper에 다른 스킬의 상태를 참조해 modifier가 변경되는 기능 추가
* SacredMark 수치에 따라 최종뎀 적용되게 함
* 어드밴스드 블레스 빠진것 추가
> fix: 비숍 스킬

- dpmModule/jobs/aran.py
실수로 딜레이가 두번 복사되어 들어가면서 타수 자리에 퍼뎀이 들어감
이와 별개로 Skill에 인자 갯수 안맞을때 빌드 에러가 터져야함
> fix: 아란 파이널 블로우(아드레날린) 타수

- dpmModule/jobs/adele.py
* 게더링-블로섬 사이에 디바이드 사용 못하는것 적용
* 게더링-블로섬 사이에 다른 DamageSkill을 사용할 수 없도록 함
* 전분 참조 링크 변경
> fix: 아델 게더링-블로섬

- dpmModule/jobs/captain.py
- dpmModule/jobs/michael.py
- dpmModule/jobs/nightlord.py
- dpmModule/jobs/nightwalker.py
- dpmModule/jobs/paladin.py
- dpmModule/jobs/pathfinder.py
- dpmModule/jobs/phantom.py
- dpmModule/jobs/shadower.py
- dpmModule/jobs/sniper.py
- dpmModule/jobs/soulmaster.py
- dpmModule/jobs/striker.py
- dpmModule/jobs/viper.py
- dpmModule/jobs/wildhunter.py
- dpmModule/jobs/windBreaker.py
- dpmModule/jobs/zero.py
제로까지 끝마쳤습니다. 
미하일
* 영메 렙차 적용여부
나이트로드
* 써든레이드 미구현
* 베놈 타수 분리 필요
팔라딘
* ~어드밴스드 차지 미구현 (컴뱃 영향은 안받음)~
* ~생츄어리 미적용~
패스파인더
* 기능상 이상은 없으나 여러 패시브 스킬들이 혼합되어 있어 정리 필요
섀도어
* 써든레이드 미사용
바이퍼
* 파이널어택 미적용
* 럭키 다이스 미적용
와일드헌터
* `super(core.DamageSkillWrapper, self).__init__(skill, 3)` 오류로 인한 테스트 불가
* 드릴 컨테이너, 재규어 맥시멈 미구현
* 윌 오브 리버티 미사용
제로
* 어드밴스드 스톰 브레이크, 어드밴스드 어스 브레이크 전기지역 스킬 도트화해야함
> 컴뱃 오더스 적용 (2)

- dpmModule/jobs/phantom.py
제가 팬텀을 몰라서 실수를 했었네요. 팬텀 캐릭터로 쓸컴뱃 구해서 직접 써봤고 느와르 카르트에는 적용되지 않는 것을 확인했습니다.
> 느와르 카르트는 컴뱃 미적용

- dpmModule/jobs/kaiser.py
fix #326
* 쿨감 적용
* 변신/비변신 딜레이 다른 스킬들 적용
* 모프 게이지 수급 스킬 정확하게 적용
* 카탈라이즈에 빠진 크확 20% 추가
* 아이언 윌이 모프 게이지 따라 데미지% 변동되도록 함
* 리서플스위치:공격모드의 변신시 추가 보공이 비변신에도 적용된것 수정
* 파이널 피규레이션에 벞지 미적용되던것 수정
* 마제스티 오브 카이저로 초기화되는 스킬 정확하게 적용
* 소울 컨트랙트, 인퍼널 브레스, 윌 오브 소드
* 가디언 오브 노바 각각 공격주기 정확하게 적용
* 윌 오브 소드:스트라이크 일반모드 폭발 퍼뎀 수정
* 인퍼널 브레스 딜사이클에 추가
* 인퍼널 브레스 장판뎀 추가
* 페트리파이드 딜사이클에 추가
* 프로미넌스 딜사이클에 추가
* 판테온 딜사이클에 추가
* 마제스티 오브 카이저, 인퍼널 브레스는 비변신에만 사용
> fix: 카이저 스킬

- dpmModule/jobs/archmageTc.py
* 체인 라이트닝에 프로스트 이펙트 적용되지 않은것 수정
* 공격-중첩감소-블리자드 순으로 항상 연결되도록 함
* 스택 증감을 onJustAfter 타이밍으로 일괄 변경
* onAfter으로 하면 데미지 계산 직전에 스택이 줄어들어 스택이 낮게 적용되는 문제가 있었음
* 에픽 어드벤처에 쿨감 적용 안되게 수정
* 라이트닝 스피어 키다운 총 시간 8010ms가 되도록 변경
> fix: 썬콜 빙결 중첩

- dpmModule/jobs/archmageFb.py
- dpmModule/jobs/archmageTc.py
- dpmModule/jobs/bishop.py
- dpmModule/jobs/blaster.py
- dpmModule/jobs/jobclass/adventurer.py
* 후보 스킬들과 가중치를 입력하면 가중치에 따라 순서대로 스킬이 시전되는 방식
* 이때 스킬의 쿨타임이 돌지 않아야 하므로 편법으로 _indirect_use에서 쿨타임을 강제로 변경함
* 불독, 썬콜, 비숍에 언스테이블 메모라이즈 추가
* 불독 코드 리팩토링
* 불독 딜사이클 수정
* 엔버링크 쿨마다 쓰는게 더 좋음
* 썬콜 코드 리팩토링
* 썬콜 딜사이클 수정
* 불독과 같은 이유로 쿨마다 사용
* 비숍은 기존 딜사이클 유지하는게 더 좋음
> feat: 언스테이블 메모라이즈 구현

- dpmModule/jobs/captain.py
fix #330 
* 로디드 다이스 패시브 추가
* 컨티뉴얼 에이밍 소환수에 적용 안되게 수정
* 배틀쉽 봄버 쿨타임, 지속시간 수정
* 럭키 다이스 딜레이 990ms 추가
* 노틸러스 컴뱃 수치 수정
* 스트레인지 봄 딜사이클에 추가
* 데드아이 딜레이 수정
* 불릿 파티 공격주기 수정
* 캡틴 디그니티 발동 목록에 헤드샷, 불릿 파티, 데드아이가 빠진것 수정
* 퀵 드로우 구현, 가능하면 헤드샷/스트봄/데드아이 전에 사용
* 노틸러스 어썰트 <-> 노틸러스 쿨타임 페널티 추가
> fix: 캡틴 스킬

- dpmModule/jobs/viper.py
* 트랜스폼, 스티뮬레이트 완충 적용 안되던것 수정
* 더블 럭키 다이스-인핸스 기댓값 적용
* 게이지 변동되는 스킬 목록 수정
* 파이널 어택 적용되는 스킬 목록 수정
* 5차 스킬 딜레이 수정
* 완충시에도 에너지 충전되는 스킬 명시적으로 표현
* 유니티 오브 파워 실제 쿨타임과 맞추고 Rule로 제어
* 에너지 오브 딜레이 수정
* 에너지 오브 트랜스폼 켜져있을때만 사용가능
* 서펜트 정확히 종료되게 함
* 딜사이클
* 스티뮬레이트 게이지 1000 이하에서 사용
* 트랜스폼은 쿨마다 사용하는게 최종뎀 때문에 더 좋음
> fix: 바이퍼 스킬

- dpmModule/jobs/angelicbuster.py
- dpmModule/jobs/ark.py
- dpmModule/jobs/cannonshooter.py
- dpmModule/jobs/captain.py
- dpmModule/jobs/eunwol.py
- dpmModule/jobs/jobbranch/pirates.py
- dpmModule/jobs/mechanic.py
- dpmModule/jobs/striker.py
- dpmModule/jobs/viper.py
* 오버드라이브에 쿨감이 적용되면서 페널티 지속시간을 단순 쿨타임 뺄셈으로 적용이 불가능해짐
* OverdriveWrapper의 get_modifier에서 판단하는 방식으로 변경
> fix: 오버드라이브 페널티

- dpmModule/jobs/wildhunter.py
- dpmModule/kernel/core.py
* 재규어 새로 구현
* SummonSkill의 Tick을 이용해 캐릭터 딜레이와 관계없이 별개의 딜레이를 가지고 동작하도록 함
* 어나더 바이트 새로 구현
* 현재부터 8초 전까지의 모든 중첩 확률이 실패할 확률을 바탕으로 스택 계산
* 재규어 스톰으로 추가 소환된 재규어도 어나더 바이트 디버프 추가되게 함
* 재규어 포획으로 받는 벞지 추가
* 재규어 스톰 패시브 빠진것 추가
* 재규어 맥시멈 추가
* 드릴 컨테이너 추가
* 안쓰게 된 core.TimeStackWrapper 제거
> fix: 와헌 스킬

- dpmModule/jobs/ark.py
* 연계시 선입력이 불가능하며, 270ms 미만의 딜레이를 가지는 스킬에 한해 +30ms의 추가 딜레이 적용
> fix: 아크 연계 딜레이 블래/카데나와 기준 동일하게 적용

- dpmModule/jobs/pathfinder.py
fix #176 
fix #46 
fix #122 
* 쿨감 적용
* 코드 순서 정리
* 카디널 디스차지 컴뱃 값 잘못 입력된것 수정
* 카디널 포스 스킬 딜레이 실험 기반으로 수정
* 클라상으로도 cancelableTime 210ms, 블래에만 있는 updatableTime 60ms로 어느정도 맞아떨어짐
* 렐릭 에볼루션의 마법 화살 추가 발사가 항상 적용되던것 수정
* 에디셔널 디스차지/블래스트/트랜지션 발동 조건을 게임 로직과 동일하게 맞춤
* 에인션트 포스, 인챈트 포스 modifier 상수 분리
* 에인션트 포스 하이퍼가 인챈트 포스에도 적용되도록 수정
* 콤보 어썰트(블래스트)에 에인션트 포스 modifier 적용된것 인챈트 포스로 수정
* 레이븐 템페스트에 누락된 에인션트 포스 modifier 적용
* 엣지 오브 레조넌스 다른 스킬 사용중에 시전 가능한것 반영해 딜레이 제거
* 콤보 어썰트(디스차지)(화살) 타수 수정
* 콤보 어썰트(트랜지션) 타수 수정
* 콤보 어썰트 딜레이 활대/화살 공격 각각 분리해서 적용
* 상태 전환시 쿨감되는 스킬에 트리플 임팩트 빠진것 추가
* 트리플 임팩트가 사용 후 약 540ms 후에 쿨타임이 돌아가는 것을 반영
* 카디널 블래스트가 렐릭 게이지 쌓지 않던것 수정
* 에인션트 가이던스 활성화 게이지가 렐릭 차지가 최대일때도 쌓이던것 수정
* 딜레이,퍼뎀,타수 수정
* 퍼뎀 수정
* 딜레이에 공속 적용
* 렐릭 게이지 소모하지 않던것 수정
* 항상 렐릭 게이지 1000을 가정하고 최종뎀 적용하던것 사용시 게이지 참조하도록 수정
* 딜레이에 공속 적용
퍼뎀 수정
* …
> Fix: 패스파인더 스킬

- dpmModule/jobs/battlemage.py
* 코드 순서 정리
* 오버로드 마나가 데스, 블랙 매직 알터에도 적용되게 수정
* 데스가 소환수가 아닌 공격에 반응해 나오는 것으로 변경
* 데스 발동 조건을 더 정확하게 적용
* 마스터 오브 데스 지속시간 도중 어둠 속성 공격으로 데스의 쿨타임이 줄어들도록 함
* 마스터 오브 데스 도중 데스의 최종뎀 50% 증가하는 효과 구현 방식을 변경
* 블로우류 스킬의 마스터 오브 데스 적용 로직을 간소화
* 배틀킹 바 2타에도 파이널 어택이 터짐
* 배틀킹 바 딜레이 수정
* 다크 제네시스 추가타가 표식을 터트릴수 있는 것 반영
* 추가타가 표식을 터트리는 것을 단순 데미지*확률로 표현하는게 불가능해 Roulette 객체 만듬
* 다크 제네시스 딜레이 수정
* 다크 제네시스 패시브로 강화되는 스킬에 컴뱃 누락된것 추가
* 다크 제네시스에 쿨타임 리듀스 하이퍼 적용
* 유니온 오라의 마력 증가량 수정
* 블랙 매직 알터 한번에 2개 설치 가능해진 패치 반영해 딜레이 변경
* 블랙 매직 알터가 다크 제네시스 추가타를 발동시킬 수 있는것 반영
* 블랙 매직 알터 공격간격 이동시간 0.8초 외에 대기시간 반영
* 그림 리퍼 마스터 오브 데스 적용중에 공격간격 50%, 지속시간 증가 안되는것 적용
* 다크 제네시스, 배틀킹 바 사용 후에 텔레포트 사용
* 소울 컨트랙트를 유니온 오라에 맞춰 사용
* 버프 사용 우선순위 변경
> fix: 배틀메이지 스킬

- dpmModule/jobs/mercedes.py
* 엘리멘탈 고스트를 최종뎀 증가가 아닌 잔상 데미지 이어붙이는 것으로 처리
* 연산량이 많이 늘어나긴 하는데, 일단 맥뎀 생각해서 구현해둠
* 엘리멘탈 나이트 2개체 소환되게 함
* 스킬 딜레이 전부 수정
* 쿨감 받는 스킬 전부 적용
* 엘리멘탈 고스트 도중 연계 딜사이클 적용
* 디버프 리필 연계 딜사이클 적용
* 크리인, 엘고, 이르칼라, 소울 컨트랙트 맞춰쓰게 함
> fix: 메르세데스 스킬

- dpmModule/item/Absolab.py
- dpmModule/item/Arcane.py
- dpmModule/item/Default.py
- dpmModule/item/ItemKernel.py
- dpmModule/item/RootAbyss.py
- dpmModule/jobs/zero.py
* 제로가 보조무기에서 보공,방무 한번 더 받는것 적용
* 어파스 콤보에서 씹히는 어시 제거
* 콤보 구현 방식 변경 - 일일이 이어붙이게 함
* 자동 연결되는 스킬을 미리 이어붙여두면 중간에 끊을수가 없어짐
* 알파,베타 스탯 적용 다른 방식으로 구현
* 이렇게 해야 무보엠/유니온 최적화가 더 잘됨
* 스킬 딜레이 전부 수정
* 기본 도핑에 영메 포함했으므로 인탠시브 타임 제거
* 리밋브 쿨타임 가속 효과를 더 정확하게 적용
* 크리티컬 바인드를 평균 가동률이 아닌 베타가 적용하는 디버프로 변경
* 조인트 어택을 사용하기 전에 무조건 베타로 변경하도록 함
> fix: 제로 스킬

- dpmModule/jobs/zero.py
* 소용돌이가 3초 내내 타격하는 것으로 계산되어 비정상적으로 높게 측정됨
* 실제로는 작은 소용돌이 2타, 큰 소용돌이 1타로 들어가는 것에 가까움
* 소환 스킬로 하면 타수를 고정하기가 어려워서 그냥 DamageSkill로 취급함
* 리밋브 이전에 베타 상태를 강제함
> fix: 제로 소용돌이 타수, 리밋브 베타 강제

- dpmModule/jobs/demonslayer.py
* 데몬 슬래시에 최종뎀 10%를 빼는것과 최종뎀-10%를 적용하는 것은 다름
* `*0.9`와 `/1.1`의 차이, 이 경우에는 후자가 맞음
> fix: 데몬슬레이어 리메인타임 계산

- dpmModule/jobs/demonslayer.py
코드 가독성을 높였으며, 테섭이 그대로 들어온다면 어웨이크닝에도 데몬 슬래시 강화가 적용되기 때문에 `AW_MODIFIER` 줄을 `AW_MODIFIER = DS_MODIFIER + core.CharacterModifier(armor_ignore = 50, boss_pdamage = 50)`로 단순화시킬 수 있습니다.
> 데몬 슬래시 modifier 분리

- dpmModule/jobs/kinesis.py
* 끌어당긴 몹당 공격주기 감소 120ms
* 공격주기 계산이 몹을 끌어당긴 다음 처리됨
* 회복의 축복 회복량 수정
#428
> fix: 키네시스 로오그, 회복의 축복

- dpmModule/jobs/pathfinder.py
* 블래/카데나/아크와 동일한 cancelableTime 연계
* 선입력이 불가능하므로, 연계가 이어질때 +30ms 추가
> fix: 패스파인더 연계 딜레이 조건 타직업과 통일

- dpmModule/jobs/demonslayer.py
* 슬래시 뎀퍼가 대부분 사라졌으므로 hint의 pdamage 낮춤
> fix: 데몬슬레이어 최적화 hint

- dpmModule/jobs/bowmaster.py
- dpmModule/jobs/jobclass/adventurer.py
- dpmModule/jobs/pathfinder.py
- dpmModule/jobs/sniper.py
- dpmModule/kernel/core.py
* 이볼브를 공용 EvolveWrapper를 사용하도록 리팩토링
* 프리저/피닉스의 공격주기는 1710ms로 확인됨 (클라, 인게임 모두 확인함)
* 레이븐의 공격주기는 1800ms로 확인됨 (마찬가지)
* 레이븐의 타수가 1인데 4로 적혀있던것 수정
* 패스파인더 레이븐 템페스트 도중 이볼브 사용불가, 레이븐 템페스트가 이볼브 잡아먹게 수정
* 패스파인더 이볼브도 칠때마다 렐릭 게이지 채워줌
* 레이븐 템페스트가 사용 가능하면 이볼브를 쓰지 않는 규칙 추가
* SkillWrapper에 set_disabled 메소드 추가 (쿨타임 바꾸지 않으면서 종료만)
fix #465
> fix: 모험가 궁수 소환수

- dpmModule/jobs/soulmaster.py
* 기존에는 샐댄과 엘리시온이 겹쳐지지 않게 사용했으나, 둘의 쿨타임이 150/180으로 애매해 샐댄이 쿨마다 사용되지 못했음
* 엘리시온의 지속시간이 샐댄의 남은 쿨타임보다 짧으면 기다렸다가 샐댄을 먼저 쓰는 방식으로 변경
* 결과적으로, 샐댄의 가동률이 올라가고 엘리시온의 가동률은 떨어지며 전체 dpm은 올라감
fix #459
> fix: 소울마스터 딜사이클

- dpmModule/jobs/blaster.py
* 리볼빙 캐논 매크로를 활용하면 훨씬 빨리 준비됨
1~2 사이 120ms
2,3,4,5,6 각각 210ms
합 1170ms
> fix: 블래스터 버닝 브레이커 준비 딜레이

- dpmModule/jobs/cadena.py
* 봄을 떨구는 동작과 터지는 것을 분리
* 웨버 터지는것에 영향이 있음
* 브릭 딜레이가 강제이동(캔슬 불가능)+폭발(캔슬 가능) 딜레이로 구성된 것을 반영
> fix: 카데나 봄브릭

- dpmModule/jobs/zero.py
제로는 해방 이전의 거의 모든 스펙에서 카벨모를 착용해서 보공 30퍼를 더 받습니다.
현재 템셋을 갈아엎기에는 다른 할일이 많으니 일단 직접 적용하는 것으로 대신했습니다. 방무 -10퍼는 카루타 모자 옵션을 빼는 것입니다.
스타포스 및 스탯 차이는 감안하지 않았지만 기존 3카5앱보다는 더 현실적인 수치라고 생각됩니다.
> 제로 4카5앱 임시 구현

- dpmModule/jobs/bowmaster.py
- dpmModule/jobs/pathfinder.py
- dpmModule/jobs/sniper.py
- dpmModule/jobs/wildhunter.py
- dpmModule/jobs/windBreaker.py
* 크리티컬 리인포스의 크뎀 증가량에 샤프 아이즈의 컴뱃으로 증가한 크확이 빠진것 수정
* 샤프 아이즈 하이퍼가 잘못 적용된것도 수정
* 윈브 윈드월 공격 중 1개는 100%로 들어가는것 반영
* 윈브 윔 사출확률 계산에 패시브 레벨 고려하도록 함
* 지금 패시브 어빌을 안쓰므로 dpm에 영향은 없음
* 윈브 스인미 1타에 윔, 스톰브링어 터지는것 반영
> fix: 크리티컬 리인포스, 윈드브레이커

- dpmModule/jobs/battlemage.py
* 블랙 매직 알터, 그림 리퍼의 공격이 물리 속성인것 반영
* 다크 라이트닝이 암흑 속성인것 반영
* 암흑 속성 공격이 마스터 오브 데스 도중 데스의 쿨타임을 감소시킴
fix #494
> fix: 배틀메이지 마스터 오브 데스

- dpmModule/jobs/flamewizard.py
- dpmModule/jobs/michael.py
- dpmModule/jobs/nightwalker.py
- dpmModule/jobs/soulmaster.py
- dpmModule/jobs/striker.py
- dpmModule/jobs/windBreaker.py
```
Before
윈드브레이커 4630644109357.117 10.23809289932251초
After
윈드브레이커 4623937350989.113 10.796057224273682초
비교대상
나이트워커 5262358101723.929 14.780503511428833초
```
현재 윈브 팔랑크스는 5단위마다 계산되는데, 1단위로 바꿀 때 얼마나 느려질지 궁금해서 실험해본 결과 차이가 거의 없었습니다.
시간이 늘어나긴 했지만 수용 가능한 범위라고 판단되어 PR을 올립니다.
추가로 텍스트 Palanks를 Phalanx로 교체했습니다.
> Wb phalanx

- dpmModule/jobs/adele.py
- dpmModule/jobs/angelicbuster.py
- dpmModule/jobs/aran.py
- dpmModule/jobs/archmageFb.py
- dpmModule/jobs/cannonshooter.py
- dpmModule/jobs/hoyoung.py
- dpmModule/jobs/ilium.py
- dpmModule/jobs/shadower.py
* 아크메이지(불, 독)의 엘리먼트 앰플리피케이션에 현행 로직과 동일하게 파이어 오라에는 적용되지 않는다는 설명이 추가됩니다.
* 앰플이 패시브로 적용되어 있어 파이어 오라에서 앰플 상승치를 뺐습니다.
* 섀도어의 암살에서 연계한 절개가 25레벨 기준 공격 발생 횟수가 1회에서 4회로 증가되고 데미지가 3800%에서 950%로 감소됩니다.
* 캐논슈터의 ICBM가 25레벨 기준 공격 발생 횟수가 4회에서 6회로 증가되고 데미지가 2400%에서 1600%로 감소됩니다. 준비 동작의 무적 시간이 공격 속도에 영향을 받는 현상, 사용 즉시 맵을 이동할 경우 이동한 맵에 오염 지역이 생성되는 현상이 수정됩니다.
* 아란의 부스트 엔드-헌터즈 타겟팅이 마스터 기준 공격 발생 횟수가 5회에서 7회로 증가되고 데미지가 1500%에서 1070%로 감소됩니다. 사용 중 맵을 이동할 경우 가끔 클라이언트가 종료되는 현상, MP가 공격 발생 횟수에 비례해 소모되는 현상, 다른 캐릭터에게 폴암 이펙트 위치가 다르게 보이는 현상, 최대 HP가 가장 높은 적을 우선 공격하지 않는 현상이 수정됩니다.
* 엔젤릭버스터의 에너지 버스터가 25레벨 기준 공격 횟수가 12회에서 15회로 증가되고 데미지가 1100%에서 900%로 감소됩니다.
* 아델의 마커 공격 횟수가 3회에서 6회로 증가되고 데미지가 1000%에서 500%로 감소됩니다.
* 일리움의 그람홀더가 25레벨 기준 공격 횟수가 6회에서 12회로 증가되고 데미지가 2000%에서 1000%로 감소됩니다.
* 본섭 기준 `1000+40n%`인데 코드상에는 `1000+25n%`로 …
> KMS 1.2.340

- dpmModule/jobs/phantom.py
1. 패시브 스킬 리턴문의 불필요한 공백을 제거했습니다.
2. 추후에 사용될 가능성이 있는 스틸 스킬들을 미리 등록했습니다. 변수명을 원래 이름으로 변경했습니다.
> 팬텀 코드 가독성 개선, 스틸스킬 옵션 추가

- dpmModule/jobs/zero.py
* 쉐스로 이어지지 않는 피어스에는 skipActionFrame 적용되지 않음
* 새로 정리된 자료 기준으로 어파스 타임라인 재작성
* 알파 콤보를 어파스에서 (문스-피어스-쉐스)*3-문스 로 변경
* dpm 4.7%정도 높음
* 1.2.338 패치의 쉐스 변경으로 가능해짐
* MoonStrike, PierceStrike의 연계/비연계 딜레이 분리
> fix(zero): 알파 콤보 변경

- dpmModule/character/characterKernel.py
- dpmModule/jobs/archmageFb.py
- dpmModule/jobs/globalSkill.py
- dpmModule/jobs/mercedes.py
- dpmModule/kernel/core/graph_element.py
SpiderInMirror, SeedRing, Genesis Skill must be instantiated,
but may not be included in the graph build depending on chtr.
This patch adds the feature to determine
whether a skill is included in the graph based on chtr.
resolve #557
> feat: filter elements with ensure()

- dpmModule/character/characterKernel.py
* 링크스킬, 하이퍼스탯, 유니온배치 없는 기준 65% 이하일때 크확소울 사용
* 8000기준 전직업 dpm 하락 없는 것 확인됨
fix #518
> fix: 무기 소울 크확 기준 변경

- dpmModule/jobs/adele.py
* 레조넌스 10초마다 사용은 고정 조건이므로 쿨감 적용하지 않음
* 인게임에서 샤드(원더)에 쿨감이 적용되지 않음
* 딜사이클에 샤드 추가
* 게더링-블로섬 히트율 조정
> fix(아델): 스킬 정보, 딜사이클

- dpmModule/jobs/nightlord.py
resolve #585
유니온 8000 기준
Before 4731734208282.821
After 4800193027567.682
스프레드 지속시간 중에는 발동하지 않음
> 나이트로드 다크 플레어 추가

- dpmModule/jobs/globalSkill.py
`ensure()` 함수는 어차피 `chtr`을 인자로 받으므로 Builder 단계에서 따로 보내줄 필요가 없습니다.
수정 후 스인미와 같은 방식으로 선언해주면 정상적으로 작동하는 것을 확인했습니다.
> GenesisSkillBuilder: chtr 인자가 필요없음

- dpmModule/kernel/core/skill_wrapper.py
when the stack is full, cooltimeLeft should not decrease
> fix: stackable skill cooltime logic

- dpmModule/jobs/captain.py
* rapid fire delay was 150, should be 120
* Quick Draw scheduling
* since kms 1.2.338, Quick Draw can be used during Rapid Fire. accordingly, the use of Quick Draw during Rapid Fire is applied to increase the final damage applied to summon skills.
> Fix captain

- dpmModule/jobs/xenon.py
* 스킬 사용 우선순위 수정
* 불필요한 스킬 제거
* 불필요한 protect_from_running 제거, cooltime=-1로 변경
* 불필요한 Rule 제거
* 하이퍼스탯 스탠스 5레벨 투자
* 오버로드 모드 도중 에너지 미감소 적용
* 오버로드 모드 도중 에너지 증가 주기 4초 -> 2초 되는것 적용
* 아마란스 제너레이터 사용시 초과분 에너지는 충전되지 않는것 적용
* 멜트다운 익스플로전 사용하지 않도록 Rule 추가
> fix(xenon): supply stack, skill priority

- dpmModule/jobs/xenon.py
* 오파츠 코드에 벞지 적용
* 딜사이클 200초 주기로 오버로드 끝자락에 극딜 사용
* 엑스트라 서플라이, 아마란스 제네레이터 사용 빈도를 최적화
* 홀로그램 융합 타수를 허수아비 기준 680타로 변경
* 에너지가 부족해도 오파츠 코드를 사용 가능했던 것 수정
* 메가 스매셔 도중 오파츠 코드가 꺼지는 것을 방지
* 에너지 충전 로직을 인게임과 동일하게 맞춤
* 스택이 최대치일 경우 틱이 0으로 고정되어, 스택이 소모되거나 제한이 늘어날 때 즉시 한칸이 충전됨
> fix(xenon): dealcycle, skills

- dpmModule/jobs/bowmaster.py
* 애로우 레인, 퀴버 풀버스트, 실루엣 미라주의 공격 간격을 인게임과 동일하게 맞춤
* 아머 피어싱의 인게임 로직을 반영
* 폭시, 레인, 퀴버풀, 미라주, 가이디드, 스인미가 쿨타임을 돌리고
* 최종뎀 발동은 폭시, 스인미에만 들어가나, 스인미에 들어갈 확률은 0에 가까우므로 폭시에만 적용
> fix(bowmaster): apply armor piercing logic

- dpmModule/jobs/paladin.py
* 마이티 묠니르를 스택형 스킬로 변경
* 홀리 유니티가 꺼져있을 때는 마이티 묠니르가 풀스택이 되지 않는 정도로만 사용
* 그랜드 크로스, 소울 컨트랙트를 홀리 유니티 주기에 더 잘 끼워넣도록 함
* 블레스드 해머(패시브)에 파이널 어택이 터지는것을 적용
> fix(paladin): 딜사이클, 파이널어택

- dpmModule/jobs/angelicbuster.py
- dpmModule/jobs/captain.py
- dpmModule/jobs/hero.py
- dpmModule/jobs/mechanic.py
- dpmModule/jobs/paladin.py
fix(angelicbuster): buff priority
fix(captain): NautilusAssult scheduling
* ensure SoulContracy sync
* prevent Nautilus disturbing NautilusAssult cooltime
* NautilusAssult_2 appears when NautilusAssult is ended
fix(hero): SoulContract usage
* ensure sync with SwordlOfBurningSoul and ComboInstinct
fix(mechanic): MagneticField remain time
fix(paladin): SoulContract stability
* when synchronizing SoulContract and GrandCross,
avoid the occasional use of only A
> fix multiple jobs

- dpmModule/character/characterKernel.py
* Some passive skills are affected by the ability's passive level.
* Therefore, the passive skill build must be done after applying the ability.
> fix(character): build passive after ability

- dpmModule/jobs/globalSkill.py
- dpmModule/jobs/kain.py
#728 작업 중 rebase를 잘못하는 바람에 엉망이 돼버려서 새 브랜치로 다시 올립니다.
변경사항
---
* 크레스트 오브 더 솔라 추가 (단일 몬스터 상대 기준)
* ~~제로의 초월자 륀느의 기원으로 발동하는 추가 타격이 오라 웨폰으로 인한 오라 파동에는 발동되지 않게 됩니다.~~ 이미 적용중
* 보우마스터의 아머피어싱에 현행 로직과 동일하게 자신이 직접 공격하는 스킬에만 발동된다는 스킬 설명이 추가됩니다. - 확인중
* [발현] 스캐터링 샷으로 정해진 개수보다 많이 생성될 수 있는 현상이 수정됩니다.
* 데몬어벤져 시드링: 본섭 패치후 #727 에 추가할 예정
> KMST 1.2.115 (재업)

- dpmModule/character/characterKernel.py
* get_weapon_base_att() was always returning weapon att
* it should return max(att, matt) because
Illium's magic curcuit references weapon matt
> fix: get_weapon_base_att()

- dpmModule/jobs/luminous.py
* Overload Mana is applied to Liberation Orb(A)
> fix(luminous): Overload Mana relation

- dpmModule/jobs/demonslayer.py
* Cerberus triggered by Demon Awakening should not have a action delay
> fix(demonslayer): Cerberus(Awakening) delay

- dpmModule/jobs/jobutils.py
- dpmModule/jobs/luminous.py
* fix(luminous): Light and Darkness stack
* should reset stack on cooltime reset, not on skill use
* does not affect dpm result
* fix: apply runtime_modifier to auxilary attack
* reference original skill's `_runtime_modifier_list`
* cannot copy `_runtime_modifier_list` because we don't know order between `create_auxilary_attack()` and `add_runtime_modifier()`
> fix luminous, create_auxilary_attack()

- dpmModule/jobs/aran.py
* implement AdrenalineSkillWrapper
* clarify skill damage from passive
* apply ADRENALINE_BOOST_PASSIVE skill damage to all aran skills
* apply passive level to 하이 마스터리
* optimize buff skill priority
* optimize rule to sync Soul Contract and Hunters Targeting
* start simulation with 900 combo
> fix(aran): fix overall code

- dpmModule/jobs/ark.py
* fix AbyssSpell's attack interval and duration (total attack count: 12>13)
* add very small damages from GustSpell and AbyssSpell
* not sync MemoryOfSource to InfinitySpell and use MemoryOfSource prior to InfinitySpell
* sync soul_contract to ForeverHungryBeast
* adjust rules of ForeverHungryBeast and EndlessPain
* adjust schedule of Flora/Specter form
* use skills controlled by 'controller' prior to other skills
* use other chain skills prior to EndlessPain
> fix(ark): skills, deal cycle, priority

- dpmModule/jobs/blaster.py
* passive afterimage attack enemies that have not been hit
* therefore, it should not be activated when attacking a single target
fix #801
> fix(blaster): AfterImageShock

- dpmModule/jobs/ilium.py
- 글로리윙이 발동되면 `is_absorbed` 가 남은 지속시간으로 할당됨
- 남은 지속시간이 양수라면, 흡수 버프를 리턴
- 음수라면(=남은 지속시간이 없으면) `disabledModifier` 를 리턴
Fix #805
> Fix soul of crystal buff remain time

- dpmModule/jobs/adele.py
아델의 무기상수가 여태 1.34로 알려져 있었으나 나제불님님님께서 측정한 결과 1.30이 맞다고 합니다.
출처 https://blog.naver.com/oe135/222385428301
> 아델 무기상수 수정

- dpmModule/jobs/jobbranch/warriors.py
* 방무가 15%로 고정돼있던 것을 클라이언트 값에 맞게 수정했습니다. (`10+d(x/5)`)
* 최종 데미지가 소수점 버림으로 되어있던 것을 소수점 올림으로 수정했습니다. (`u(x/5)`)
> fix-auraweapon: 방무 및 최종뎀 오류 수정
